### ISSUE TITLE
Mirror the favicon to the static site

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#121]
This isn't referenced anywhere directly, so doesn't get mirrored from the spidering process.

**Comment by tmtmtmtm** [comment]
We could commit this file directly to the static repo, but that runs the risk of getting blown away at some point, especially if we switch to a complete "clean and rebuild" approach, like we've talked about.

Probably best to explicitly add a `link rel="icon" type="image/x-icon" href="favicon.ico"` to the header, though @zarino might know if that's the correct incantation these days, or whether there's something better / with more widespread support, etc.

**Comment by zarino** [comment]
`<link rel="icon" type="image/x-icon" href="/path/to/favicon.ico">` is indeed the correct incantation. (No need for `shortcut` any more, since it was an IE-only aberration, and IE9 will cope without it as long as the link has a `type` of `image/x-icon`)

**Comment by tmtmtmtm** [comment]
@zarino, great, thanks. Now added.
