### ISSUE TITLE
Fix error on /about

### ISSUE THREAD

**Issue by abibroom** [everypolitician/everypolitician#124]
> To see where we have have data for, pick a country.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon : over to you…

**Comment by MyfanwyNixon** [comment]
> To see how far we've got with any specific country, locate it on this page.

**Comment by tmtmtmtm** [comment]
I think this should be as much about which countries we have as about what we have within a country, so I've gone for "To see how far we’ve got, choose a country". (https://github.com/everypolitician/viewer-sinatra/commit/9f5aa797b1954f1aed8d1ef4dc626b09cb440918) @abimysoc, does that work better for you?

**Comment by abibroom** [comment]
Dude, I was only pointing out the typo, not suggesting a complete copy rewrite :)

**Comment by tmtmtmtm** [comment]
Ah, I didn't even notice the doubled 'have' — I thought you were making a point about grammar :)
