### ISSUE TITLE
Stickers!

### ISSUE THREAD

**Issue by zarino** [everypolitician/everypolitician#144]
For when we meet people in, like, real life.

@Gemmamysoc – do you have specific dimensions in mind? Previously we've done custom-cut stickers with a shape that closely follows the outline of the logo. Or, if you want something cheaper (more stickers!!!) we could keep it to a stock shape, like a circle or round-rect?

**Comment by Gemmamysoc** [comment]
No specific dimensions or shapes in mind. But would be good to keep costs down - so perhaps stick to a stock shape. I quite like hexagonal shaped ones. But I'll leave you to decide what you hink works best/suits the website!

**Comment by Gemmamysoc** [comment]
We used this company last time: http://www.harris-screenprint.co.uk/

**Comment by zarino** [comment]
[4.5cm circular vinyl sticker](http://www.awesomemerchandise.com/Circular-45mm-Vinyl-Stickers): 

![everypolitician-45mm-sticker](https://cloud.githubusercontent.com/assets/739624/10050543/c89c8b02-6214-11e5-9268-c22f16e99788.png)

And for mySociety, a [custom shaped 10cm long vinyl sticker](http://www.awesomemerchandise.com/Custom-Shaped-Vinyl-Stickers-10cm):

![mysoc-sticker-fitted](https://cloud.githubusercontent.com/assets/739624/10050554/d4668b40-6214-11e5-9dc4-e860a1e56a30.png)

If you're happy, @Gemmamysoc, I'll email you the source files.

**Comment by davewhiteland** [comment]
A drive-by observation that might be a bit late (sorry): in our text copy we have not been using a space between the words when writing the name "EveryPolitician".

http://everypolitician.org/about.html
https://www.mysociety.org/2015/09/07/how-quickly-can-we-get-to-200-countries-on-every-politician/

**Comment by zarino** [comment]
@davewhiteland Ah. The logo on the website has a space in it. But the text further down the page has no space! So it looks like this was never really standardised. Removing the space makes it clear that "EveryPolitician" is actually a thing of its own, rather than just "every politician".

I've opened a new ticket to replace the website header logo and the Github avatar with a space-less version (https://github.com/everypolitician/everypolitician/issues/158).

Here's how the sticker would look without a space:

![everypolitician-45mm-sticker](https://cloud.githubusercontent.com/assets/739624/10068575/5c3370fa-629d-11e5-965a-3a00739d2e4c.png)

And the mysociety one again (to the same scale):

![mysoc-sticker-fitted](https://cloud.githubusercontent.com/assets/739624/10050554/d4668b40-6214-11e5-9dc4-e860a1e56a30.png)

**Comment by Gemmamysoc** [comment]
Looking good! Has @tmtmtmtm approved the EveryPolitician one?

**Comment by Gemmamysoc** [comment]
Also @paullenz wanted to see the designs before they go to print. What are your thoughts, Paul? Cheers!

**Comment by Gemmamysoc** [comment]
Thinking more about the EveryPolitician one - I think having a bold background colour could make it more striking. So could it perhaps be the EP green with a white logo?

**Comment by zarino** [comment]
Oooooh! We've never done a reversed EveryPolitician logo before. I guess this is how it'd look:

![everypolitician-45mm-sticker](https://cloud.githubusercontent.com/assets/739624/10071372/3f6bd516-62b1-11e5-8962-0d0e2b29bfbe.png)

I've switched to an all-white version of the mySociety logo, because the dots are effectively invisible on the vibrant green background.

And the white one for comparison:

![everypolitician-45mm-sticker](https://cloud.githubusercontent.com/assets/739624/10068575/5c3370fa-629d-11e5-965a-3a00739d2e4c.png)

**Comment by paullenz** [comment]
Love the mySoc sticker my preference is for the green EP sticker

**Comment by zarino** [comment]
The final EveryPolitician stickers ended up looking like this:

![everypolitician-sticker-4-up](https://cloud.githubusercontent.com/assets/739624/10097121/c5695e6e-636e-11e5-88a4-fbad1279f668.png)
