### ISSUE TITLE
Auto-update based on changes in upstream sources

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#150]
If, for example, parlparse data changes, we should trust that enough to automatically flow through to EP. From other sources (e.g. morph) we could trigger a PR for manual review.

This is potentially a mix of webhooks (e.g. for Parlparse) and scheduled rebuilds.

**Comment by chrismytton** [comment]
The high level plan here is to have a "rebuilder" which accepts a request to an endpoint like `/Australia/Senate`. This "rebuilder" will then perform the following steps:
1. Clone the https://github.com/everypolitician/everypolitician-data repo
2. `bundle install` dependencies for that repo
3. Run an as yet unspecified `rake` task to rebuild data for the requested country
4. Commit changes to a branch on GitHub
5. Push the branch to GitHub
6. Create a Pull Request for the branch on GitHub

A prerequisite for this is #171, which will avoid the need to do a separate commit to update the `countries.json` file.

This will also have a lot of shared functionality with the [app-manager](https://github.com/everypolitician/app-manager) codebase, so initially that can be copied over but in the medium term it should be refactored into a shared library or similar.

**Comment by tmtmtmtm** [comment]
implemented in https://github.com/everypolitician/rebuilder
