### ISSUE TITLE
Document 'names.csv'

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#160]
Explain that the file exists, and what it is.

**Comment by tmtmtmtm** [comment]
@davewhiteland is this sufficiently documented now?

**Comment by davewhiteland** [comment]
Yes, bot blog covered this here https://medium.com/@everypolitician/i-make-lists-of-humans-names-4b061212baf3 -- but this should be linked-to from elsewhere, so closing this issue but noting that everypolitician/everypolitician-docs#19 is still open and relevant.
