### ISSUE TITLE
Separate webhook registration and dispatch from Pull Request previews

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#175]
## Problem

There is some confusion when trying to explain/understand the [app-manager](https://github.com/everypolitician/app-manager) repository at the moment as it combines two mostly unrelated parts
1. app-manager
2. everypoliticianbot
## app-manager

One part of it manages 3rd party applications, e.g. gender-balance, accepting new data submissions from them and sending webhooks to them to notify then when there's new data available.
## everypoliticianbot

The other part of it is the bits that manifest themselves in various places on GitHub as @everypoliticianbot.

This currently includes:
- Triggering "deploys" to viewer-sinatra when there's an everypolitician-data Pull Request
- Auto-merging pull requests from trusted sources (not currently in use, but the code is there).
- Updating viewer-static

In the future this might also include:
- Automatically updating everypolitician-data when there are upstream changes #150 
- Automatically updating `countries.json` when there's a new everypolitician-data pull request. #171 
- Leaving summaries of changes everypolitician-data pull requests will make #174 
## Summary

We should separate these two bits out to reduce the confusion and make them independently maintainable. The app-manager should only be responsible for allowing 3rd party applications to register their interest in receiving webhooks and allowing them to submit updates to the data. everypoliticianbot should only carry out low level tasks and probably won't have a public facing we interface.

**Comment by chrismytton** [comment]
We now have the [`pull_request_preview`](https://github.com/everypolitician/pull_request_preview) app, which handles creating previews of Pull Request in viewer-sinatra and [`countries_json_updater`](https://github.com/everypolitician/countries_json_updater) for updating `countries.json` in everypolitician-data pull requests. The app manager is now solely responsible for webhook registration and dispatch.

**Comment by tmtmtmtm** [comment]
> The app manager is now solely responsible for webhook registration and dispatch

@chrismytton should we consider renaming it to 'webhook-manager' or something instead?

**Comment by chrismytton** [comment]
@tmtmtmtm Yep good call, have opened https://github.com/everypolitician/everypolitician/issues/267 to track that.
