### ISSUE TITLE
Differentiate the "merged to master" DATASOURCE update

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#192]
It would be very useful if the automated DATASOURCE update from when a everypolitician-data PR gets merged to master were differentiated (presumably just with a different commit message) from the previous "work in progress" commits.

**Comment by tmtmtmtm** [comment]
@chrismytton I'm assuming this should be fairly trivial?

**Comment by chrismytton** [comment]
Yea, should be _quite_ easy, at the moment the message is hardcoded in the [`GithubFileUpdater`](https://github.com/everypolitician/app-manager/blob/1f84879a93d8d11cf9e6428bcdf3d7491e294fa2/lib/github_file_updater.rb#L39-L41) but shouldn't be too tricky to make that configurable.

**Comment by tmtmtmtm** [comment]
No longer an issue, now that we're merging directly to master and closing the PR.
