### ISSUE TITLE
Drag and drop interface for reconciliation

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#195]
Currently we generate a CSV file that needs to be hand edited in order to match up names from different sources. Instead we want a nice drag and drop interface that allows you to match incoming data to existing data.

We've started work on this in the `reconciliation-csv` branch https://github.com/everypolitician/everypolitician-data/tree/reconciliation-csv.

**Comment by zarino** [comment]
I've been working on this in the [195-reconciliation-ui branch](https://github.com/everypolitician/everypolitician-data/compare/195-reconciliation-ui?expand=1).

![screen shot 2015-11-04 at 12 08 37](https://cloud.githubusercontent.com/assets/739624/10937725/cc8c9bf0-82ec-11e5-83d2-98830ccfb4eb.png)
