### ISSUE TITLE
Reconciliation: Find other close matches

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#198]
At the moment fuzzing just returns the best match — ideally it could let you know if there are other very close matches and let you select between them. 

i.e. if the top match is 96% and the next best match is only 16%, then it's almost certainly the first person. But if there's a 96% match a 95% match and then a 16% match, it would be good to offer both of the top ones, rather than only the 96%.

**Comment by tmtmtmtm** [comment]
There's an undocumented `find_all_with_score` method that will give this to us. So, for example, in the Northern Irish Assembly, `fuzzer.find_all_with_score('Mark H. Durkan').map { |who, s1, s2| [who[:id], who[:name], s1, s2] }.uniq { |r| r.first }` returns:

```
=> [["11589", "Mark Durkan", 0.9411764705882353, 0.7857142857142857],
 ["25143", "Mark Durkan", 0.9411764705882353, 0.7857142857142857],
 ["13857", "Mark Robinson", 0.3157894736842105, 0.4285714285714286],
```

letting us know we'll need to choose between the first two in each case.

**Comment by chrismytton** [comment]
Currently we're pulling out the top 3 matches but would be good to do something a bit smarter so leaving this ticket open for now.

**Comment by tmtmtmtm** [comment]
'Top 3' has turned out to be Good Enough, so I'm going to close this for now, and we can re-open a new ticket for any specific improvements we think of later.
