### ISSUE TITLE
Don't retry webhooks on app-manager if they fail

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#212]
If a webhook times out or fails we should just discard it. It will be re-tried the next time there's a push to `master` on everypolitician-data anyway, which is usually multiple times per day.

**Comment by tmtmtmtm** [comment]
Discarding makes sense if someone is subscribed to notifications of _any_ change. However we'd like to support per-legislature/country webhooks at some stage (#221), and I'm a little worried that if you miss a webhook on those, another one might not come around again for months.

So I think we should only send once if you're subscribed to everything, but ensure that when we do something more fine-grained we re-examine whether to bring back retries in that case.
