### ISSUE TITLE
Reconciler: Can't reconcile Costa Rica

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#213]
```
cd data/Costa_Rica/Assembly                                                                              
rm sources/reconciliation/wikimedia.csv
bundle exec rake clobber default
open sources/reconciliation/wikimedia.html
```

Although there are multiple fuzzed rows, none of them appear in the reconciler:

![cost rica screen shot 2015-11-12 at 21 29 47](https://cloud.githubusercontent.com/assets/57483/11131931/fa197702-8984-11e5-9539-78e3cc1cb415.png)

**Comment by tmtmtmtm** [comment]
Same for Gibraltar, Niue, St Helena, Turks&Caicos

**Comment by chrismytton** [comment]
Notably these are all places that don't have an `id` in the source data, so I suspect these may magically start working once https://github.com/everypolitician/everypolitician/issues/225 is fixed.
