### ISSUE TITLE
Reconciler: Highlight any "existing person" card that has already been matched to someone else

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#215]
Any person in "existing data" known to have already been matched to a different "incoming data" person should be highlighted in some way, so that it's more obvious when there's likely to be a mistaken double match.

**Comment by zarino** [comment]
Note from Chris:

> If they were matched in the current reconciliation then they're in `window.votes`.
> 
> If they were already matched in a previous reconciliation then they will be in the `window.reconciled` array, which is the same structure as `window.votes`
