### ISSUE TITLE
Warn if a legislature build generates any new IDs, or removes any existing ones

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#222]
As a first step towards https://github.com/everypolitician/everypolitician/issues/174, simply warn of any changes to IDs (additions or removals)

**Comment by chrismytton** [comment]
Example of this in actions - https://github.com/everypolitician/everypolitician-data/pull/3381#issuecomment-173710496 (the formatting could do with a bit of work!)

**Comment by tmtmtmtm** [comment]
Woooo!
