### ISSUE TITLE
Reconciler: Convert legacy CSVs with no source id

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#225]
We've now converted all the legacy CSVs which have an `id` in the incoming data. The only ones that remain are where there's currently no `id` in the incoming data. To fix these we'll need to add an `id` to the incoming data, then it should get automatically converted by the code added in https://github.com/everypolitician/everypolitician-data/pull/1238.

Once these CSVs have been converted we can then delete the code that was added in https://github.com/everypolitician/everypolitician-data/pull/1238 for converting in-place.
- [x] data/Costa_Rica/Assembly/sources/reconciliation/wikimedia.csv
- [x] data/Gibraltar/Parliament/sources/reconciliation/wikidata.csv

---
- [x] data/Albania/Assembly/sources/reconciliation/official-8.csv
- [x] data/Botswana/Assembly/sources/reconciliation/official.csv
- [x] data/Falkland_Islands/Assembly/sources/reconciliation/official.csv
- [x] data/Niue/Assembly/sources/reconciliation/wikipedia-2014-election.csv
- [x] data/Saint_Helena/Legislative_Council/sources/reconciliation/official.csv
- [x] data/Saint_Lucia/Assembly/sources/reconciliation/images.csv
- [x] data/Turks_and_Caicos_Islands/Assembly/sources/reconciliation/wikidata.csv

List generated with the following command:

```
for file in $(git grep -l confidence); do echo "- [ ] $file"; done
```

**Comment by tmtmtmtm** [comment]
Adding an `id` in the SELECT will have the nasty effect of generating an incorrect legacy-ID. 

I suspect the best fix to _that_ is to spit out the existing legacy-IDs to a fixed file that can't change in the future, as it makes no sense for those to be being generated at run time now with potential changes.  (#230)

**Comment by tmtmtmtm** [comment]
These are all done — but we still need to remove the temporary scaffolding.
