### ISSUE TITLE
Make a pombola-light for Zimbabwe

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#228]
Based on the [spike we did](https://github.com/chrismytton/pmo-static) for a static site that updates from EveryPolitician we want to convert [KuvakaZim](http://www.kuvakazim.com) over to work as a static site.

This should be a case of porting the existing styles and markup over to jekyll but it might also require some design time to tidy things up.

**Comment by chrismytton** [comment]
- [x] Import all info pages and blog posts
- [x] Get the site deploying to GitHub pages
- [x] Import people from the existing site
- [x] Make search work for people, organizations and areas https://github.com/mysociety/kuvakazim/issues/3
- [ ] ~~Transfer existing Disqus comments across https://github.com/mysociety/kuvakazim/issues/5~~
- [x] Setup Google Docs spreadsheet to act as the admin panel for the site
- [x] Integrate WriteInPublic #229

**Comment by tmtmtmtm** [comment]
I'm marking this as 'done'. We can open new tickets for anything extra we need.
