### ISSUE TITLE
Ensure `gender` is consistent everywhere

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#238]
@davewhiteland reports inconsistency across different legislatures with the `gender` field.

**Comment by davewhiteland** [comment]
I think it's been fixed since I encountered it a couple of weeks ago or so: I had found `M` or `F` for gender, but `git grep` shows there's no output CSV files with that pattern (e.g., `git grep ',M,'`) so if you concur, can close this.

**Comment by tmtmtmtm** [comment]
I'm not sure why you're not getting any results from that. `git grep -l ',M,'` gives me results from Congo-Kinshasa, Malawi, and Sweden.

And `git grep -h gender data/**/ep-popolo*.json | sort | uniq -c | sort -n -r` gives all sorts of other variations that will also need to be tidied up:

```
21621       "gender": "male",
5113       "gender": "female",
 599       "gender": "M",
 331       "gender": "Homme",
 327       "gender": "Male",
 179       "gender": "Female",
 147       "gender": "Femme",
  85       "gender": "F",
  31       "gender": "f",
  26       "gender": "m",
   1       "gender": "r",
   1       "gender": "Ni",
   1       "gender": "M ,",
```
