### ISSUE TITLE
Bot that closes open pull requests if they're identical

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#250]
When the rebuilder runs twice in quick succession for a legislature it _might_ create two identical pull requests. We should have a bot that goes through pull requests on a regular basis and closes any that are identical to existing ones.

**Comment by tmtmtmtm** [comment]
I think it's probably enough to be identical in terms of file _names_ rather than file _contents_ — i.e. a later request can simply supersede the prior one.

Or, I guess if it's a superset of the files that would probably work too.

**Comment by chrismytton** [comment]
Also need to make sure this only works with bot-generated pull requests and ignores others.

**Comment by chrismytton** [comment]
This is now done. [`pull_request_cleaner`](https://github.com/everypolitician/pull_request_cleaner) will check any new pull requests and see if there are any other Pull Requests with a matching title from the same author. If there are then a bot will leave a comment on the older pull request linking to the newer one and then close the old pull request.

**Comment by chrismytton** [comment]
Note that this won't do anything with existing open Pull Requests that only specify the country in the PR title. It will only work for future Pull Requests that will also include the legislature.
