### ISSUE TITLE
viewer-sinatra: Reference Pull Request when updating DATASOURCE on master

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#266]
When we close a Pull Request and push a commit directly to `master` it would be good to reference the Pull Request number from the commit to make it easier to find if necessary.

**Comment by tmtmtmtm** [comment]
Example: https://github.com/everypolitician/viewer-sinatra/commit/431e746e6462f350c93ea6d62a6840563d360343

**Comment by chrismytton** [comment]
Ooops, I've referenced the everypolitician-data pull request without giving the full url.

Perhaps it would be best to reference both the everypolitician-data pull request (correctly) and the viewer-sinatra one.
