### ISSUE TITLE
Switch EveryPolitician::Wikidata.scrape_wikidata to use Wikisnakker

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#269]
We now have a series of helper functions in wikidata-fetcher that mean Wikidata scrapers are only a [handful of lines long](https://github.com/tmtmtmtm/russian-duma-wikidata/blob/master/scraper.rb). 

Having encapsulated the part that actually does the Wikidata lookups, we should now switch that to use Wikisnakker behind the scenes.

**Comment by chrismytton** [comment]
Now using Wikisnakker - https://github.com/everypolitician/wikidata-fetcher/compare/722abbe2f0d1481fa1b6fbd160cdc77b4029a059...master
