### ISSUE TITLE
Previous/next term navigation is unweildy

### ISSUE THREAD

**Issue by zarino** [everypolitician/everypolitician#293]
![screen shot 2016-01-22 at 15 50 51](https://cloud.githubusercontent.com/assets/739624/12515364/f1c921ba-c11f-11e5-9c98-c6f2ce21685a.png)

This was added in very hastily a while back, and we've never got round to revisiting.

My first stab would probably be to shorten the links. Something like:

![screen shot 2016-01-22 at 15 50 12](https://cloud.githubusercontent.com/assets/739624/12515341/d7b7cf06-c11f-11e5-8173-f72aa0e1aa42.png)

But it might be that this whole system of navigating needs a re-think.

**Comment by davewhiteland** [comment]
Have to be a bit careful here not to imply that the "previous term" was the term immediately prior to this one; likewise for next. (Usually they will be, but there's no way EveryPolitician is actually enforcing that).

So unfortunately I think those particular abbreviations are ambiguous; sorry :-(

**Comment by tmtmtmtm** [comment]
Actually, I'm pretty sure that'll be safe. We don't currently have any skipped terms, AFAIK, and I'd be very hesitant to ever introduce any.

**Comment by zarino** [comment]
If you're worried, we could use the date range instead of "Next term" / "Previous Term"?

**Comment by tmtmtmtm** [comment]
what do you think of something like "Earlier" / "Later"?

**Comment by zarino** [comment]
Pull request here: https://github.com/everypolitician/viewer-sinatra/pull/5258
