### ISSUE TITLE
pull_request_preview: Retry pull request creation if countries.json change not detected

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#298]
Currently when we try to create a preview pull request we check to see if countries.json has been updated. On rare occasions countries.json has been updated but the GitHub API hasn't reflected that. It would be good if we could either delay running the creation job to give the API a few seconds to catch up, or retry creating the Pull Request a couple of times to ensure we don't miss any updates.

**Comment by tmtmtmtm** [comment]
we no longer have this workflow
