### ISSUE TITLE
Make sure all EveryPoltician repos have a Usage section where appropriate

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#299]
Currently a lot of them just have "TODO: Write usage instructions here", e.g. https://github.com/everypolitician/everypolitician-popolo#usage.

**Comment by chrismytton** [comment]
https://github.com/everypolitician/combine_popolo_memberships/issues/4

**Comment by chrismytton** [comment]
https://github.com/everypolitician/wikisnakker/issues/21

**Comment by tmtmtmtm** [comment]
@chrismytton — all the repos mentioned here have a Usage section now. Can this issue be closed now, or are there other repos that should be listed here too?

cc: @davewhiteland

**Comment by chrismytton** [comment]
I've just grepped for "TODO: Write usage instructions here" and nothing turned up, so closing this now. If there are other places that need updating those can be ticketed separately.
