### ISSUE TITLE
webhooks: Sign webhooks with an HMAC signature

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#300]
[Follow GitHub's lead](https://developer.github.com/webhooks/securing/) and sign our webhooks with HMAC. This would require people to add a secret to their webhooks, but would mean that they could authenticate that they came from EveryPolitician.

We could also create a Rack middleware which handles checking the signature for you and you just give it the secret, much like [`rack-github_webhooks`](https://github.com/chrismytton/rack-github_webhooks#usage).

**Comment by chrismytton** [comment]
[This is how GitHub sign webhooks](https://github.com/github/github-services/blob/f804613a178f0f46acc53eded85308d5db25929a/lib/service/http_helper.rb#L74-L78)

**Comment by davewhiteland** [comment]
:+1:  want (I want to be able to trust the webhook's payload)
