### ISSUE TITLE
Explain JSON and CSV download options on term page

### ISSUE THREAD

**Issue by zarino** [everypolitician/everypolitician#324]
In https://github.com/everypolitician/everypolitician/issues/289#issuecomment-186178384 @tmtmtmtm correctly noted that the list of politicians has diverged enough from a plain table that the "Download as CSV" button no longer really makes sense.

![screen shot 2016-02-22 at 11 28 22](https://cloud.githubusercontent.com/assets/739624/13217008/6ea21594-d957-11e5-8514-2cc1f9209ba9.png)

CSV is still useful for a really quick "just a list of names" use-case, but JSON is actually a better representation of the politician data displayed in this section. It feels like we should display both options. But if we do, we need to explain why they're different. And also explain the slightly unexpected fact that the JSON download includes data for _all historical terms_ not just the currently visible one.

Perhaps something like this?

![screen shot 2016-02-22 at 11 27 55](https://cloud.githubusercontent.com/assets/739624/13216996/54d962ca-d957-11e5-8d37-0bc4601fcde0.png)

**Comment by tmtmtmtm** [comment]
Yep — I think the approach works — now just a matter of finding the right text :)

For the JSON one, I think we can just drop the "on all memberships" from end, and that works OK.

The CSV one is a bit trickier. I'd probably also drop the "in Excel", but the part that's going to be harder to get across is what's actually in it, without listing everything (There's more than just names, parties, and areas — currently also email, twitter, facebook, image, gender, start/end date)

cc @MyfanwyNixon @davewhiteland

**Comment by tmtmtmtm** [comment]
btw for those joining us at this point in the discussion, it's not so much the changes to the layout of the politicians themselves that are triggering this change, but that we're now also going to be adding meta-information about how much data we have, and that will include things that aren't in the CSV. So it'll be quite odd to explain what % of parliament.uk identifiers we have, for example, and then give a 'Download this data as CSV' link that doesn't include those.

**Comment by MyfanwyNixon** [comment]
How about:

**Download as CSV**
Essential [or top-level?] data on current politicians. Perfect for quick analysis.

And as you suggest,

**Download as JSON**
All the data we hold on this legislature, including historical data

**Comment by zarino** [comment]
> Essential [or top-level?] data on current politicians. Perfect for quick analysis.

FWIW it's not necessarily "current" politicians – if you're looking at a term in the past, the CSV will contain politicians from that (historical) term.

**Comment by tmtmtmtm** [comment]
Perhaps just "these politicians" to show that it's in the context of the people on the current page?

**Comment by MyfanwyNixon** [comment]
'These' seems good.

**Comment by davewhiteland** [comment]
Adjective for the kind of data (fields) "_Selected_ data on current politicians. Perfect for quick analysis".  Maybe? 

Maybe link on "selected data" (with a `target` to not blast away this window?) to the description of the fields at http://docs.everypolitician.org/data_summary.html ...?

**Comment by MyfanwyNixon** [comment]
Only trouble with 'selected' is that people might think they can select what they need?

**Comment by davewhiteland** [comment]
@MyfanwyNixon  Yes :-(   Maybe "key"? "Core"?

**Comment by MyfanwyNixon** [comment]
Both are good :)

**Comment by tmtmtmtm** [comment]
@zarino: other than finding the right wording, I'm assuming actually implementing this is going to be super simple, right?

**Comment by zarino** [comment]
@tmtmtmtm: Fairly simple! We don't have bootstrap or anything, so we don't get it for free, but it's not hard to do from scratch.

**Comment by tmtmtmtm** [comment]
@zarino: great. is it something you have time to squeeze in this week, or do we need to schedule it for next sprint?

**Comment by zarino** [comment]
@tmtmtmtm: I could potentially do it this week. Do you have wording in mind?

**Comment by tmtmtmtm** [comment]
@zarino: we can fix up the wording later if required, but I'd go for now with "Core data on these politicians, perfect for quick analysis",  and "All the data we hold on this legislature (including historic)"

**Comment by zarino** [comment]
Pull request here: https://github.com/everypolitician/viewer-sinatra/pull/4763
