### ISSUE TITLE
instructions: rename the two `type` fields

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#325]
We currently have two different `type` fields, with different semantics, which leads to confusion.

``` json
    {
      "file": "morph/gov.nu.csv",
      "create": {
        "type": "morph",
        "scraper": "tmtmtmtm/niue-assembly",
        "query": "SELECT * FROM data"
      },
      "type": "membership"
    },
```

We should replace the `type` within the `create` block as `method` (it's to do with _how_ we create the file if it doesn't exist).

The second is a little trickier. The key thing to convey is that this isn't explaining the _contents_ of the files, but how we're treating them (in theory we could read the same file twice and do different things with it each time)

**Comment by davewhiteland** [comment]
Suggestions: (one terse, one verbose)
- `for`
- `data_type_provided` or `data_type_extracted`

**Comment by tmtmtmtm** [comment]
I've made the first `from`. I think `generates` is probably best for the second.

**Comment by tmtmtmtm** [comment]
I did this in https://github.com/everypolitician/everypolitician-data/pull/119823, but I'm actually not convinced it really does make anything clearer. No longer having the ambiguity is probably enough.
