### ISSUE TITLE
Provide a CSV containing the current memberships of a term

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#338]
Originally reported here https://github.com/everypolitician/everypolitician-data/issues/918

At the moment we provide a CSV for each term which contains _all_ of the memberships for a given term. So if someone has changed party during a term then there will be two rows for them in the term CSV, one for each party.

It would be useful if there was a file which contained a snapshot of just the _current_ state of the legislature, i.e. each person just appears in there once with their current party information. Something like `current.csv` in the legislature directory, probably linked to from the `countries.json` file.

**Comment by lucychambers** [comment]
Should be "Latest" rather than "Current" 
![bitmoji](https://render.bitstrips.com/v2/cpanel/9936640-126778335_11-s4-v1.png?transparent=1&palette=1&width=246)
