### ISSUE TITLE
Signpost how people can filter

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician#339]
It is unclear here - to a lay person such as me - what exactly I can filter on (I was expecting a drop down) some signpost text e.g. enter a name or place or party

![screenshot 2016-03-11 17 14 26](https://cloud.githubusercontent.com/assets/909811/13709644/f462e3e4-e7ac-11e5-99d7-288072251ece.png)

**Comment by zarino** [comment]
Maybe `Filter by name, location, etc…` ?

**Comment by tmtmtmtm** [comment]
Moved to https://github.com/everypolitician/viewer-sinatra/issues/5264
