### ISSUE TITLE
Don't allow multiple parties to have the same name or id

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#347]
For example there are [these two parties in Aland which have the same id](https://github.com/everypolitician/everypolitician-data/blob/e1ccb5dbfd6951d6a1c60a482838c0353c09a383/data/Aland/Lagting/ep-popolo-v1.0.json#L2780-L2789) and their names only differ in capitalization. There is also one other party in Aland which is duplicated because of capitalization.

We should probably just error loudly if we detect this and then manually intervene to fix the cause.

![screen shot 2016-03-16 at 09 25 19](https://cloud.githubusercontent.com/assets/22996/13806003/14184c2e-eb59-11e5-8229-dafb0ef922bb.png)

**Comment by tmtmtmtm** [comment]
Whatever way we fix this, I think we do need to allow two different parties to have the same name. Particularly as we add more historic information we're going to hit multiple cases where several different parties in a country have been called the same thing. We could perhaps warn loudly if they both have the same name _at the same time_, as I suspect that's much more unlikely.

**Comment by tmtmtmtm** [comment]
I think this is largely solved by https://github.com/everypolitician/everypolitician/issues/428
