### ISSUE TITLE
Separate build and deploy steps on viewer-sinatra

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#348]
I just encountered a problem where building the static version of the site on Travis failed because it ran out of memory. I've fixed this now (https://github.com/everypolitician/viewer-sinatra/pull/5346) but it made me realise that we only know if this has broken when the changes are already on `master`. This is because [the `release.sh` script](https://github.com/everypolitician/viewer-sinatra/blob/a36c863b9093bae2d2cfd3e56328de0b7ffc370b/scripts/release.sh#L41-L47) only builds the static site on `master`.

I propose that we always _build_ the static version of the site but only _deploy_ it if we're on `master`. That way we know of the build step has broken before we merge the change.

**Comment by tmtmtmtm** [comment]
Oh, that definitely sounds nice.

**Comment by chrismytton** [comment]
Bit more info on this:

The build is performed by [this part of `release.sh`](https://github.com/everypolitician/viewer-sinatra/blob/a36c863b9093bae2d2cfd3e56328de0b7ffc370b/scripts/release.sh#L15-L18) and the deploy is done by [this part of `release.sh`](https://github.com/everypolitician/viewer-sinatra/blob/a36c863b9093bae2d2cfd3e56328de0b7ffc370b/scripts/release.sh#L19-L25).

You can determine if you're on `master` or not by using [Travis' default environment variables](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables).

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/viewer-sinatra/pull/14708
