### ISSUE TITLE
Speed up countries.json build

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#359]
At the moment it can take 5+ minutes to build `countries.json`. This is because the [`countries_json_updater` app](https://github.com/everypolitician/countries_json_updater) has to take the following steps for _every_ pull request that is opened or updated:
1. Clone everypolitician/everypolitician-data which is quite a large repo
2. `bundle install` the dependencies for that repo
3. Run `bundle exec rake countries.json` to actually update `countries.json`
4. Commit the result and push it back

So in order to speed up the build we ideally want to remove steps 1 and 2. Some possible ideas

Rather than regenerate the whole `countries.json` file from scratch we could instead assume it already exists and just change the part of it that are affected by the current pull request. So if we're updating UK/Commons we just change the `sha` to whatever the tip of the pull request branch is and set the `lastmod` to the time of the last commit in the pull request. This would then avoid needing to clone the everypolitician-data repo as we should be able to do this using the GitHub API.

**Comment by tmtmtmtm** [comment]
See also https://github.com/everypolitician/everypolitician/issues/431

**Comment by tmtmtmtm** [comment]
Thanks @mhl 

I'll look more closely at the code later, but as a quick note, you're closing Issue 451 in the wrong repo with this at the moment.

**Comment by chrismytton** [comment]
We can get a small speed boost by doing https://github.com/everypolitician/countries_json_updater/issues/3.

**Comment by tmtmtmtm** [comment]
I think we've done enough on this for now
