### ISSUE TITLE
Progressive enhancement

### ISSUE THREAD

**Issue by dracos** [everypolitician/everypolitician#36]
It would be <a href="http://mysociety.github.io/coding-standards.html">great</a> if:
- [ ] the "drag & drop" only appeared if the browser can handle it (otherwise showing the standard file upload box alone)
- [ ] the form could have the correct HTML attributes (method=post and enctype=multipart/form-data) to enable basic submission
- [ ] the form response could not just be JSON, but show the same HTML page you get when JavaScript is available.
- [ ] the form response enabled non-JS submission utilising an iframe, or PopIt returning HTML to a form submission.

**Comment by tmtmtmtm** [comment]
Agreed. We have a wider problem though, in that we couldn't come up with sensible way to submit the JSON to PopIt other than via JavaScript. So a fallback is really just going to be a "Sorry — there's nothing we can do". Suggestions welcome.

**Comment by dracos** [comment]
Umm, well, you have a bigger problem than that, in that any JavaScript upload is going to fail due to Same Origin Policy: "XMLHttpRequest cannot load https://us-presidents.popit.mysociety.org/api/v0.1/imports. Origin http://openpoliticians.org is not allowed by Access-Control-Allow-Origin."
The correct way to do it would be to set up some form of authentication on PopIt (e.g. oAuth) so that openpoliticians can request access on the user's behalf to post the data. That would then work for the purposes of this ticket also.

**Comment by tmtmtmtm** [comment]
Are you logged into that PopIt, with admin permissions on it, when submitting? If so, then there's definitely something wrong — that should be working (and is for me). 

If not, then the problem is that I haven't been able to work out yet how to catch the different return codes in jQuery, to display better error messages, as they're coming from preflight OPTIONS call, rather than the POST (#10).

**Comment by dracos** [comment]
Ah, thought I was, but I wasn't, sorry. Yes, has worked for me.

An easier suggestion would be for a popit to have a web form for JSON import (perhaps it already does), then that could be where the JSON is submitted – of course you'd then get a PopIt results page rather than an openpoliticians one, but that would seem to provide the same level of experience.

**Comment by tmtmtmtm** [comment]
Sure — I'd definitely support PopIt adding such a thing, and suspect that that's what will happen at some point. But OpenPoliticians needs to move faster than PopIt on these things at the minute, and can't really wait for PopIt to add it. So we're going to have to do a few things in less than ideal ways to start with, and just put them out there in a Release Early, Release Often way, and evolve towards what we'd really like.

**Comment by dracos** [comment]
How about this? Your response HTML form submits to an iframe on the same page – this means it could go ahead as a standard form submission accompanied by some explanatory text, this would only need a couple of lines change to PopIt, for it to cope with a parameter as well as JSON directly.

**Comment by tmtmtmtm** [comment]
@dracos I'm afraid I can't work out what you're suggesting here. What would the addition to PopIt need to be to enable this?

**Comment by dracos** [comment]
PopIt's `imports` endpoint currently only accepts JSON directly as the body of a application/json POST. If it also accepted JSON as a parameter of a normal application/x-www-form-urlencoded or multipart/form-data form submission (express is <a href="https://github.com/mysociety/popit-api/blob/d013d2d6b18147567e092b1f3e09b1e006081ada/src/app-setup.js#L36-L37">already set up</a> in PopIt to handle both styles of input, so I would hope this is a small tweak to `import.js`), then a normal form submission could be used to submit such data to PopIt, rather than requiring something to handle direct submission.

PopIt could choose to respond to that kind of submission with an HTML page rather than a JSON response (saying "your data is now in a queue and is being imported" type thing). Then at the OpenPoliticians end, the first form submission (to Heroku currently) would return HTML, a page that contains a form containing the JSON data, that could be submitted to PopIt and work fine.

The iframe idea was if the second PopIt change I mention above wasn't done, only the first, then you could still have OpenPoliticians submit the form, just submit it to an iframe (which would then get the JSON response that PopIt returns). Let me know if that still doesn't make sense.

**Comment by tmtmtmtm** [comment]
Ah, got it now, thanks. Yep, sounds good. Chris is going to open an issue on PopIt to look at doing this.

**Comment by tmtmtmtm** [comment]
We no longer offer this form.
