### ISSUE TITLE
Display of identifiers breaking

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician#369]
![screenshot 2016-03-29 16 32 08](https://cloud.githubusercontent.com/assets/909811/14113718/15b117b4-f5cc-11e5-9526-c3d9ebcbd5c9.png)

Viewed  in Safari

**Comment by chrismytton** [comment]
Moved to everypolitician/viewer-sinatra - https://github.com/everypolitician/viewer-sinatra/issues/6274
