### ISSUE TITLE
Handle things like 'Nominated Member', 'Womens Representative' etc.

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#371]
In many countries, there's a distinction between people who were specifically elected to their legislative seat, and people who were appointed for various reasons. 

There probably isn't a one-size-fits-all version that is strictly accurate, but within EveryPolitician consistency should be the primary drive, so that people can write generic tools without knowing the subtle differences everywhere, with strict precision an extra for people who need it in a local context.

I suspect, therefore, that we should simply create optional Posts on the Legislature for things like "Women’s Representative" etc. The `organization_id` should still be set on all Memberships, so anything that isn't aware of (or doesn't care about) the `post_id` can safely ignore it, but anything that needs to know more can resolve that.

**Comment by tmtmtmtm** [comment]
Since `csv-to-popolo` 0.22, we've been able to include these as `legislative_membership_type`, so this ticket is essentially closed. But we still need to add this to the docs.

@davewhiteland can you open a ticket for doing so, link these, and then close this?

**Comment by davewhiteland** [comment]
Closed, to be documented: everypolitician/everypolitician-docs#22
