### ISSUE TITLE
Make separate Source::JSON and Source::CSV base classes for unprocessed versions

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#372]
https://github.com/everypolitician/everypolitician-data/blob/f3166e63734b22510b0448804c7efda8e9ac43a0/lib/source.rb#L83-L99

There are some places where we're using a source as-is and we don't want it to be remapped. At the moment we have to use some workarounds such as overriding `Source::CSV#fields` to return `[]` and overriding `Source::CSV#as_table` to prevent errors and remapping of fields.

It would be good to have separate base classes, one that just handles plain CSV/JSON sources and one the does all the extra processing that's required in `combine_sources.rb`.

**Comment by tmtmtmtm** [comment]
I don't really remember enough of the history here, and this whole area has changed substantially over time, but we currently have `Source::CSV` and `Source::PlainCSV` which I think is enough. If it's not, I suspect we'll want a deeper rewrite again anyway, so I'm going to close this!
