### ISSUE TITLE
Add webhooks for commit status events

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#379]
https://developer.github.com/v3/activity/events/types/#statusevent

When the status of a commit in a pull request changes we should trigger a webhook. This will allow apps to detect when the Travis CI build has passed or failed, and pave the way for auto-merging pull requests.

**Comment by tmtmtmtm** [comment]
The primary driver for this (auto-merging) isn't likely to happen now, and we haven't had any other call for this, so I'm closing this. If we ever do find we need it, we can easily resurrect the idea.
