### ISSUE TITLE
Example dates on /upload page

### ISSUE THREAD

**Issue by duncanparkes** [everypolitician/everypolitician#38]
We should give examples of an acceptable date format for the dates.

**Comment by tmtmtmtm** [comment]
At the minute dates simply get passed through to PopIt as-is, but I'm not actually sure what PopIt _does_ with dates, and whether anything other than YYYY-MM-DD is accepted. (I've raised (https://github.com/mysociety/popit.poplus.org/issues/39 against the PopIt API docs on this.)

It would also be good to accept as many date formats as possible: https://github.com/tmtmtmtm/csv_to_popolo/issues/19 deals with that (though SmarterCSV doesn't seem to have the built-in date conversion that the default Ruby CSV does...)

**Comment by tmtmtmtm** [comment]
superseded by https://github.com/everypolitician/viewer-sinatra/issues/337
