### ISSUE TITLE
Auto-merging of pull requests

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#381]
Some pull requests should be automatically merged if they come from a trusted source.

Having discussed this with @tmtmtmtm we think the best approach is to build a new app which listens for webhooks and merges pull requests that come from whitelisted sources. It should only merge a pull request once it has a `Refresh countries.json` commit and the commit status is green.

This will require adding webhooks for commit status events (https://github.com/everypolitician/everypolitician/issues/379) and adding the name of the source into the pull request title (~~https://github.com/everypolitician/everypolitician/issues/380~~ https://github.com/everypolitician/rebuilder/issues/59).

Once these bits are in place we can then whitelist pull request titles that should be auto-merged _if_ they come from @everypoliticianbot. So for example "United Kingdom (House of Commons): refresh data from parlparse" could be whitelisted, then any updates @everypoliticianbot does from parlparse would be automerged.

**Comment by tmtmtmtm** [comment]
The number of sufficiently trusted sources we have is too low (and trending towards zero, as we move to everything coming from Wikidata) so there isn't really enough value from this any more.
