### ISSUE TITLE
Add button next to person name to look up their details on OpenCorporates

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician#390]
On e.g. http://everypolitician.org/uk/commons/term-table/56.html

So that name is looked up e.g. like - https://opencorporates.com/officers?utf8=✓&q=diane+abbot&commit=Search&order=alpha

**Comment by paullenz** [comment]
Oh - we would need to strip accents out of the text string we submit for the search, as currently OC doesn't recognise

**Comment by tmtmtmtm** [comment]
I'd assume a huge % of people don't have matches there, and a large % of the ones where there is _some_ match by name would be to the wrong person (It's far from obvious that the Diane Abbot you link to, who's the secretary of a Florida foundation, is the same person as the UK politician). If we can find a way to actually cross-reference people with a high degree of accuracy, then linking the ones that _are_ matched would make sense, but I don't know how we'd go about that.
