### ISSUE TITLE
Change button text from "Download" to "Download data"

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#397]
It's not obvious _what_ you are going to download (it's actually data) so why would you click it? (Unless you've read all the stuff, and know we're all about the data, which is fine. But having the word data there wouldn't spoil that either).

Related to #396.

I was certain I had already ticketted this but I can't find the issue now, either here or in viewer-sinatra, so I have created it again.

**Comment by tmtmtmtm** [comment]
I think it also needs to be obvious that you're downloading _all_ the data for the term. I can easily imagine someone filtering the data (e.g. by Party), and then expecting the Download button to only give them that subset of people.

**Comment by tmtmtmtm** [comment]
is this closed by https://github.com/everypolitician/viewer-sinatra/pull/10637?

**Comment by davewhiteland** [comment]
@tmtmtmtm yes it is :-)
