### ISSUE TITLE
Investigate hamburger vs. logo confusion on mobiles

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#398]
On http://everypolitician.org, I've had 2 our of 2 (tiny sample size, but real world behaviour) users repeatedly attempt to click on the logo on mobiles because it looks like the notorious hamburger menu icon when rendered at the top of the screen on a small device.

Both assumed the link was broken; one, before clicking it, said "your menu has broken your screen layout, look" because it appeared to be overlaying the "EveryPolitician" heading.

Sorry.

**Comment by JenMysoc** [comment]
closing and moving to viewer-sinatra repo

**Comment by davewhiteland** [comment]
moved to everypolitician/viewer-sinatra#11912
