### ISSUE TITLE
Display a list of the user's existing instances

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#40]
Instead of giving people an input box (from which they can enter things that aren't theirs, make typos etc), simply offer them a list of the PopIts they currently have permission to post to.

**Comment by wrightmartin** [comment]
:+1: yes, this would greatly simplify the initial journey

**Comment by tmtmtmtm** [comment]
Thanks to https://github.com/mysociety/popit/issues/777 we'll hopefully be able to have this Real Soon Now!

@wrightmartin — I'm not entirely sure of the display/flow issues here though. If you had 15 mins to look at what this should look like, it would be super helpful! I'm assuming most people will have a small enough list that we could simply display them all and ask them to select one, so presumably I should just implement it as straightforward Radio buttons to start with, and then we can have fancy styling magic to make that look good?

**Comment by wrightmartin** [comment]
@tmtmtmtm we could use a type-ahead search like the one on WriteIt http://writeit.ciudadanointeligente.org/en/writeit_instances/provincia-de-buenos-aires-diputados

**Comment by tmtmtmtm** [comment]
@wrightmartin I was hoping to remove the need for them to ever type _anything_ (thus removing the option of ever submitting to a PopIt that doesn't exist, or that they're not logged in to, etc.) — they're only going to be selecting from _their_ PopIts — not the full list of all that exist. In a lot of cases, people will probably only have one PopIt anyway to choose from, and I really doubt there are many people with more than five.

**Comment by tmtmtmtm** [comment]
I've implemented this using a select box in https://github.com/mysociety/openpoliticians/tree/40-select_an_instance

I'm not 100% happy yet with the flow for rebuilding the list after you've gone off to log-in or make a new instance, but I'm not really sure how to do that better.
