### ISSUE TITLE
Investigate memory issues with Wikidata-fetcher

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#450]
# Problem

Currently, with large legislatures (e.g. [Germany](https://morph.io/tmtmtmtm/germany-bundestag-members-wikidata)), the Wikidata scraper often fails with out of memory issues, even when fetching the data in quite small batches. 

Investigate whether there's something we can do to stop this blowing up.
# Proposed Solution

??? (though see notes below)
# Acceptance Criteria

Ideally we wouldn't need to set a batch size for the Germany scraper at all. If, however, we simply are just fetching too much data in a single request (rather than there being a bug with either `wikidata-fetcher` or `wikisnakker`), it's OK to set a limit on that. It seems that that should be a lot bigger than 20 though, and it would be good if the scraper should finish in under 15 minutes.

Other interim improvements are still useful, but aren't sufficient to close this.
# Not Required

n/a
# Prerequisites

n/a
# Related Issues
- https://github.com/everypolitician/wikisnakker/pull/44 — should definitely help, but that doesn't seem like the primary cause
# Due Date

No specific date, but this is causing the build for a major country (Germany) to fail, so is of high importance.
# Design?

n/a
# Text?

n/a
# Bloggable?

Probably not unless we uncover something particularly interesting.
# Other notes

It's not clear yet whether the problem is going to be in `wikisnakker` or `wikidata-fetcher`. My guess without having dug particularly deeply is that it's likely to be the latter, and that we're holding on to data between iterations that we could just free up after writing to the database.

**Comment by chrismytton** [comment]
It seems like at the moment we might be wasting memory by defining a method for every property that we come across using [`define_singleton_method`](https://github.com/everypolitician/wikisnakker/blob/81c25b9ab25f1345fbb05a60f7aa65e8abde693e/lib/wikisnakker.rb#L110). Instead of being so explicit we could instead use `method_missing` to intercept method calls and dynamically return the property that's been requested.

**Comment by chrismytton** [comment]
I tried to do some surgery on the code to get it using `method_missing` but didn't manage to get it working properly. I think the whole property handling could do with a bigger refactor, but I don't want to mess around with it too much until https://github.com/everypolitician/wikisnakker/pull/43 is merged as that also changes the property handling code.

For the time being I'm going to merge https://github.com/everypolitician/wikisnakker/pull/44, which definitely uses less memory than before. Then we can iterate further in future PRs.

**Comment by tmtmtmtm** [comment]
https://github.com/everypolitician/wikisnakker/pull/50 is good enough for this, at least for now.
