### ISSUE TITLE
ensure every EP repo has a useful description

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#454]
So that the list GitHub shows at https://github.com/everypolitician is more helpful.

**Comment by tmtmtmtm** [comment]
Currently missing:
- [x] https://github.com/everypolitician/everypolitician-ruby
- [x] https://github.com/everypolitician/rebuilder
- [x] https://github.com/everypolitician/pull_request_preview
- [x] https://github.com/everypolitician/everypolitician-gender-summary
- [x] https://github.com/everypolitician/rebuilder-ui
- [x] https://github.com/everypolitician/ocd_lookup
- [x] https://github.com/everypolitician/pull_request_cleaner
- [x] https://github.com/everypolitician/image_cache
- [x] https://github.com/everypolitician/combine_popolo_memberships
- [x] https://github.com/everypolitician/zimbabwe-images
- [x] https://github.com/everypolitician/twitter_username_extractor
- [x] https://github.com/everypolitician/kuvakazim_updater
- [x] https://github.com/everypolitician/parlparse-webhook-receiver
- [x] https://github.com/everypolitician/parlparse-to-csv

**Comment by davewhiteland** [comment]
Done so at least every repo when listed offers some more detail (also added README to https://github.com/everypolitician/pull_request_preview)
