### ISSUE TITLE
make everypolitician PHP library

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#456]
We _need_ a PHP version of https://github.com/everypolitician/everypolitician-ruby

My main motivation for this is it's effectively a prerequisite for letting WordPress plugin devs loose on the data.

(Any passing PHP devs who would like to implement this for us, yay!)

**Comment by andylolz** [comment]
~~Should this be structured in the same way as the [python](https://github.com/everypolitician/everypolitician-python) and [ruby](https://github.com/everypolitician/everypolitician-ruby) projects, i.e. a separate PHP package for [popolo](https://github.com/everypolitician/everypolitician-popolo-python) [stuff](https://github.com/everypolitician/everypolitician-popolo)?~~ <<< 👍 

UPDATE: There’s an initial version of an everypolitician-popolo-php library here:
https://github.com/andylolz/everypolitician-popolo-php

…and I’m just starting on the everypolitician-php library here:
https://github.com/andylolz/everypolitician-php

**Comment by davewhiteland** [comment]
@andylolz yup, I think you're right to break the Popolo out like that, but you're way ahead of me before I'd even replied to that

**Comment by andylolz** [comment]
Okay cool – I’ve done initial releases of both libraries now 🚀 

https://packagist.org/packages/andylolz/everypolitician
https://packagist.org/packages/andylolz/everypolitician-popolo

**Comment by tmtmtmtm** [comment]
Woot! Thanks @andylolz 

One tiny thing to note: in the description of `everypolitician-popolo` you say it's to "Parse Popolo JSON data and navigate it with PHP". Unless you've done much more than simply porting the existing Ruby/Python, this will probably only successfully parse *EveryPolitician*-flavoured Popolo, not any other Popolo file that someone happens to find from another source. Might be better to make that a little more explicit.

**Comment by andylolz** [comment]
Ah, good point! Fixed that now.

Related to that: these libraries are lazy ports of the [python](https://github.com/everypolitician/everypolitician-popolo-python) [versions](https://github.com/everypolitician/everypolitician-python) (right down to that description!) I still need to make a pass through the ruby versions to check what I’m missing. Also, these are my first PHP libraries, so I should have a think about any modifications / extras that a PHP user might expect.

**Comment by tmtmtmtm** [comment]
Yep, there are definitely things that are new in the Ruby that haven't made it to the Python version yet.

Any suggestions for what the best way is to keep us all aware of what's happening in each version? Mailing list? Slack? Github? …?

**Comment by andylolz** [comment]
Any of the above :)

**Comment by andylolz** [comment]
Not sure, really… Do you already have an EveryPolitician slack?

**Comment by andylolz** [comment]
In fact… I’ve just tidied up my github notifications and watched all the relevant everypolitician repos, so just using github should be fine.

**Comment by tmtmtmtm** [comment]
Great. Let's try that for now, and see how it goes.
