### ISSUE TITLE
remove mailto: prefix from email values

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#459]
# Problem

There are quite a lot of email addresses sneaking in with mailto: prefixes still attached.

(Supercedes everypolitician/everypolitician-data#13827 which was the wrong repo for this issue.)
# Proposed Solution

Let's strip 'em out (I propose we can be confident that nobody has an email address with mailto: as part of the username, RFC regarding colons notwithstanding).
# Acceptance Criteria

We're aiming to have no `mailto:` prefixes in email addresses (although it's probably not wanted in a scraped URL either (such as `notes`, although I don't know we've had that problem (yet)).

So `fgrep mailto data/*/*/ep-*.json` in `everypolitician-data` should show nothing.
# Not Required

—
# Prerequisites

None
# Related Issues

None
# Due Date

None
# Design?

No
# Text?

No
# Bloggable?

No

**Comment by tmtmtmtm** [comment]
@ondenman want to try this one?

**Comment by ondenman** [comment]
Sure.

**Comment by davewhiteland** [comment]
I just edited the acceptance criteria after discussion in Slack, with @tmtmtmtm's suggestion of using `fgrep` only hitting the `ep-pololo` files.

> Acceptance criteria stats: "git grep mailto in everypolitician-data shows nothing.” …does it really matter if ‘mailto:’ shows up in morph/data.csv?
> 
> > @tmtmtmtm no; that's badly specified. You should persuade [@davewhiteland] to rewrite that
