### ISSUE TITLE
Convention on .gitignore files

### ISSUE THREAD

**Issue by octopusinvitro** [everypolitician/everypolitician#462]
Do we have a convention for `.gitignore` files?

The one I added to the gem repo ([see it here](https://github.com/everypolitician/twitter_list/blob/master/.gitignore)) is a generic `.gitignore` file for Ruby projects generated from [https://www.gitignore.io](https://www.gitignore.io).

Following Tony's suggestion, I'm asking here for your opinion, as I took all this conventions from my own [personal Ruby skeleton](https://github.com/octopusinvitro/ruby-scafold) that I use for my own projects, but maybe it is not generic enough.

**Comment by chrismytton** [comment]
We don't really have a convention for `.gitignore`. When creating gems I tend to use `bundle gem gemname`, which generates an appropriate `.gitignore` file. For things that aren't gems I tend to just add to them as needed, so for a scraper you might add `data.sqlite` or for a Ruby app you might add `.env`, but generally I'll start with nothing in those cases.

**Comment by octopusinvitro** [comment]
Closing as this was answered :+1:
