### ISSUE TITLE
More conventions: Other dot files 

### ISSUE THREAD

**Issue by octopusinvitro** [everypolitician/everypolitician#463]
The last issue on dot files, I promise :)

This is regarding the `.rspec` and `.ruby-version` files.

The `.rspec` file is generated together with `spec/spec_helper.rb` when typing `rspec --init`, but maybe it is not generic enough, as it supposes that you are using RSpec as your test framework.

The `.ruby-version` file might as well be controversial... should the version be in the `Gemfile`?

**Comment by tmtmtmtm** [comment]
I suspect we want slightly different conventions for different types of projects, but in general I don't think we should be tying things to a specific Ruby version unless it's the only version that it will work on.

**Comment by octopusinvitro** [comment]
Closing as this was answered :+1:
