### ISSUE TITLE
Archive scraped webpages

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#466]
# Problem

The websites that we scrape are constantly being updated with new information and old information is being removed. If a scraper's sqlite database is deleted then it's not possible to fully recreate it from scratch if the pages it scrapes have changed.
# Proposed Solution

Create a library that intercepts http requests and caches the response and returns it. Initially this should just cache the response in a separate (possibly orphaned) branch in the scraper's git repo, however it would be good if this was pluggable, so that in the future the pages could be cached elsewhere, e.g. Amazon S3, archive.org etc.
# Acceptance Criteria

Scrapers should be able to `require` this library and have it work out of the box with little to no configuration. The majority of scrapers use `open-uri`, so hooking into the `open` method provides an easy way to work with most scrapers.

There should also be options so that the scraper can request to _only_ used existing cached versions of the page it's scraping, or be able to request a specific version of the page from in the past.
# Not Required

At this stage we _probably_ don't need to be caching the other assets on the page (CSS, JS, images etc). We should get it working for plain HTML pages first, then caching additional assets can be a future enhancement.
# Prerequisites

None.
# Related Issues
- https://github.com/openaustralia/morph/issues/795
# Due Date

ASAP!
# Design?

No.
# Text?

No.
# Bloggable?

Eventually this should be something that everyone who's writing a Ruby scraper on Morph _wants_ to use, so at that point we should start shouting about it.

**Comment by tmtmtmtm** [comment]
https://github.com/everypolitician/scraped_page_archive
