### ISSUE TITLE
Combine more than one origin for the same source in instructions.json

### ISSUE THREAD

**Issue by octopusinvitro** [everypolitician/everypolitician#471]
# Problem

Looks like we don't have yet a good way of handling the case when we have more than one origin for the same source. For example, [this scraper](https://github.com/everypolitician-scrapers/twitter-list-spain-congreso/blob/master/scraper.rb) uses two Twitter lists to fetch Twitter handles and avatars. But the the resulting popolo file looks [like this](https://github.com/everypolitician/everypolitician-data/pull/14239/commits/925974c3da37a5ef7fcc16c45d974400f3f2f9ec#diff-c1e23b99fc0817945ed8c59bce22e2f9L55616).
# Proposed Solution

The way we would like to add them is as a list in the `sources` field of the `instructions.json` file. An example can be seen in the `instructions.json` file [for the previous example](https://github.com/everypolitician/everypolitician-data/pull/14239/commits/ec5945dd5cdb09d4d96548c99923fa85d5b050ad).
# Acceptance Criteria

Both the URLs scraped in the example should appear in the `meta[:sources]` as flat and we should check that the data comes from all the sources specified in the list.

**Comment by tmtmtmtm** [comment]
@octopusinvitro this branch was super-out-of-date to the extent that I can't even test it, so I've cleaned out all the bot-updates of `countries.json`, and rebased it over current master.
