### ISSUE TITLE
Reconciler: 'website' field unexpectedly Red

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#478]
# Problem

When reconciling the Kazakh new term in https://github.com/everypolitician/everypolitician-data/pull/14876, the 'website' field is red for everyone, even though the data is the same, and should therefore be green.

![screen shot 2016-08-01 at 09 41 13](https://cloud.githubusercontent.com/assets/57483/17288349/8a5fb950-57cc-11e6-8add-0c283ab70901.png)
# Proposed Solution

?
# Acceptance Criteria

When reconciling this data, the fields should be green where the URL is the same on both sides.
# Not Required

n/a
# Prerequisites

n/a
# Related Issues

n/a
# Due Date

n/a
# Design?

No.
# Text?

No.
# Bloggable?

No.

**Comment by tmtmtmtm** [comment]
This appears to be true for lots of other fields too:

![screen shot 2016-08-08 at 07 10 19](https://cloud.githubusercontent.com/assets/57483/17470806/43217b80-5d37-11e6-8659-f0e243ce2c82.png)

**Comment by tmtmtmtm** [comment]
I'm assuming that this broke in https://github.com/everypolitician/everypolitician-data/pull/14266, but unravelling that is making my head hurt. I'd really like this highlighting to move out of this template and into the JS file, as something that gets layered on at a different stage (cf. https://github.com/everypolitician/everypolitician/issues/480).

(An example that's fairly quick to build and shows this on the first card is Sweden.)

@chrismytton anything stand out for you at a glance here?

**Comment by davewhiteland** [comment]
To join the party late: here's a screenshot of it on every field
![screen shot 2016-08-10 at 10 59 35](https://cloud.githubusercontent.com/assets/111320/17550386/9aefb56e-5eec-11e6-8d9c-ed8bdd93a78d.png)
