### ISSUE TITLE
mechanism for viewing/noticing frequency of rebuilds per legislature

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#479]
# Problem

Currently we generally run a webhook off the _wikidata_ scraper on morph.io for each legislature, and rely on that scraper's once-every-24-hours frequency to trigger the rebuilder. 

But it's possible for this to fail: maybe the scraper running it for some reason fails to trigger it; or maybe there simply is no webhooked scraper (which happened with everypolitician/everypolitician-data#14961: none of the sources on Colombia's Senate had a webhook set up because I hadn't noticed it wasn't autoupdating. And in this case, because there's only one legislature per country in the useful "dashboard" spreadsheet it wasn't going to be picked up by a large, red entry in the `ago` column.

We need a way of noticing that a legislature is not being updated.

Incidentally I _think_ this is more about making general behaviour visible rather then setting up alerts, because as the no-update period increases, it becomes more likely that something's up... rather than knowing for certain something's gone wrong.

Two problems:
- process fix maybe that causes a legislature to not be on the spreadsheet
- better way of being alerted other than actively looking for absences/late updates 
# Proposed Solution

We have a better way of noticing if a legislature has not been updated for a while. 
# Acceptance Criteria
# Not Required
# Prerequisites
# Related Issues

This seems _mildly_ related to everypolitician/viewer-sinatra#13665 insomuch as this problem and that problem are both about visibility of the meta-data of last modified date.
# Due Date
# Design?
# Text?
# Bloggable?

**Comment by tmtmtmtm** [comment]
This information is now exposed in the `sources` section of `unstable/stats.json`
