### ISSUE TITLE
Create library for writing scraper parser classes

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#483]
# Problem

Scrapers mostly follow the same pattern of loading an html page and then running css/xpath selectors against the html. At the moment this pattern is implemented in an ad-hoc way, it would be good to create a reusable approach to this.
# Proposed Solution

Create a library that allows you to define a class which takes a url and has a way of defining mappings between property names and the css/xpath needed to find them.

An early example of this in actions can be seen in [the estonia-riigikogu scraper](https://github.com/tmtmtmtm/estonia-riigikogu/blob/8d3de9e7bc5c2834bade26aacb972874db405f9f/scraper.rb#L79-L125). This uses a slight hack where the `protected` method is used to denote properties that we want to expose.

The alternative syntax that I discussed with @tmtmtmtm a few weeks ago is as follows:

``` ruby
class PersonPage
  # Simple CSS or XPath fields
  field :name, css: '.page-header h1'
  field :faction, css: '.content a[href*="/fraktsioonid/"]'
  field :phone, xpath: '//span[contains(@class,"icon-tel")]/following-sibling::text()'

  # Looking for fields within a scope
  scope :social_media, xpath: '//h2[.="Sotsiaalmeedia"]/following-sibling::div[@class="group"]'
  field :twitter, css: 'a.twitter/@href', scope: :social_media

  # Complex lookups using raw html or nokogiri in a block
  field :something_complex do |html, noko|
    # Manually find the field in `html` or using `noko`
  end
end
```

I'm not sure what the best input for these classes is, possibly just the url to the record, or perhaps just the html that comes back from the http request/out of the scraped page archive.
# Acceptance Criteria

Creating a new scraper should simply be a case of defining a class which specifies the required fields, and the CSS/XPath to find them.
# Not Required

This doesn't need to handle retrieving the webpages or archiving them as that's being done separately by the [`scraped_page_archive` gem](https://github.com/everypolitician/scraped_page_archive).
# Prerequisites

None.
# Related Issues
- Archive scraped webpages https://github.com/everypolitician/everypolitician/issues/466
# Due Date

ASAP.
# Design?

No.
# Text?

No.
# Bloggable?

Potentially.

**Comment by tmtmtmtm** [comment]
> I'm not sure what the best input for these classes is, possibly just the url to the record, or perhaps just the html that comes back from the http request/out of the scraped page archive.

I think this should just be the HTML — we don't want to couple this to any particular implementation of where that HTML comes from. The only responsibility _this_ should have is turning the HTML into a data structure. Something else should be responsible for getting the HTML, passing it in to this, and then doing whatever it needs with the resulting data.

**Comment by chrismytton** [comment]
We've created [`field_serializer`](https://github.com/everypolitician/field_serializer) as a starting point to evolve from. You can see it in action in [this scraper for Mongolia](https://github.com/everypolitician-scrapers/mongolia-khurai-wp-multiple-terms).

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/scraped/
