### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician#487]
Very basic question: how do I cite your website? Purpose: presentation to colleagues.

**Comment by davewhiteland** [comment]
@briatte I have replied by email, but will update this issue shortly!

**Comment by davewhiteland** [comment]
"EveryPolitician" _and_ the URL seems best:

> EveryPolitician. http://everypolitician.org/

In email @briatte also pointed out the potential value of attribution from a _who-funded-this?_ point of view. mySociety's funding comes from multiple sources, of course, but the point is [those funding sources can be determined](https://www.mysociety.org/about/funding/): so perhaps another, longer, form could be:

> EveryPolitician by mySociety. http://everypolitician.org/

We're certainly keen to have the URL present in any/all citations.

**Comment by davewhiteland** [comment]
Closing this; implementation of it now in separate issues.
