### ISSUE TITLE
Scrape list of legislatures

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#5]
From http://en.wikipedia.org/wiki/List_of_legislatures_by_country or equivalent (including number of seats)

**Comment by duncanparkes** [comment]
A scraper for the list of legislatures is gradually coming together here: https://morph.io/mysociety/wikipedia_list_of_legislatures

Currently it just collects stringified versions of every entry in the UN countries table.

**Comment by tmtmtmtm** [comment]
This was replaced by https://morph.io/mysociety/wikipedia_list_of_legislatures2 (we should really rename that over the original one…)
