### ISSUE TITLE
Reference the Represent API for Canada, not OpenParliament

### ISSUE THREAD

**Issue by jpmckinney** [everypolitician/everypolitician#50]
OpenParliament pulls data from http://represent.opennorth.ca/, which has much wider coverage.

Represent's API predates Popolo, but it'd be easy to export as Popolo JSON.

The scrapers are mostly run at http://scrapers.herokuapp.com/ That app has Imago API endpoints, which follow Popolo, though they may not expose all the scraped data (would need to check): https://scrapers.herokuapp.com/people/

**Comment by tmtmtmtm** [comment]
Thanks. Is there a specific endpoint just for Parliament? That's all we're really tracking right now.

(If you know of sources for other countries that are missing, that would be great too!)

**Comment by jpmckinney** [comment]
Canada House of Commons is http://represent.opennorth.ca/representatives/house-of-commons/?limit=0

US (requires API key) https://sunlightlabs.github.io/congress/

France http://cpc.regardscitoyens.org/trac/wiki/API

Italy - ask OpenPolis

Worth checking these lists:

PMOs by Country w Websites
https://docs.google.com/a/opennorth.ca/spreadsheet/ccc?key=0Akm6uoR20ePVdE0wbnphX294bXNnRDM0aUZKaVBDZ1E#gid=0

International Transparency Organizations
https://docs.google.com/a/opennorth.ca/spreadsheet/ccc?key=0AoQuErjcV2a0dF85QTRRSEFtR3pfcjN4VHdwLVYzSXc#gid=0

The Crowdsourced International Civic, Democratic and Transparency Website List
https://docs.google.com/a/opennorth.ca/spreadsheet/ccc?key=0AkwRl6JWX8tkdGxqT1ZFUWxFbElVa3d1S1NOODQ2aVE#gid=0

PMOs & Parliaments Open Source & Download
https://docs.google.com/a/opennorth.ca/spreadsheet/ccc?key=0Akm6uoR20ePVdEd5LTQwVURJNXNacHBBbkU3aVJWUHc#gid=0

Database CSO's working on OpenGov
https://docs.google.com/a/opennorth.ca/spreadsheet/ccc?key=0AoY7j9MkwpmYdHJ6dWJTd0ZUS1VPN0NPUTRpZVRlQnc#gid=0

**Comment by tmtmtmtm** [comment]
None of these are

**Comment by tmtmtmtm** [comment]
Unless I'm missing something, none of these offer Popolo-format data. We're not simply tracking who has data / APIs etc: we're explicitly looking for Popolo, so that people building generic tools, Poplus components etc., can ensure that their tools work with the data (and to encourage other people to generate Popolo so that they can then benefit from those tools).

**Comment by jpmckinney** [comment]
Ah, sorry, I was confused by OpenParliament.ca, which only sort-of uses Popolo.

**Comment by jpmckinney** [comment]
On the other hand, https://scrapers.herokuapp.com/people/ is Popolo. For MPs, use https://scrapers.herokuapp.com/people/?memberships__organization_id=ocd-organization/e9438c08-7fa4-4189-b511-c4a24e059616 and paginate with the `page` parameter.

**Comment by tmtmtmtm** [comment]
I ended up with a very thin wrapper around the Represent scraper: https://morph.io/tmtmtmtm/represent-ca 

This fits into our standard workflow of downloading Morph data as CSV, and feeding it through https://github.com/tmtmtmtm/csv_to_popolo to generate Popolo
