### ISSUE TITLE
Library for handling tables with rowspans and colspans

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#520]
# Problem

Lots of our scrapers have to deal with tables, particularly from Wikipedia. In the simple case, this is easy. However, if the table contains rowspans or colspans, the logic gets very complicated very quickly.
# Proposed Solution

We should use a library that handles that for us. I'd be very surprised if something suitable doesn't already exist, but I've only been able to find python examples so far:
- https://gist.github.com/wassname/5b10774dfcd61cdd3f28
- https://github.com/dbpedia/table-extractor
- https://github.com/bcicen/wikitables
- https://github.com/chrisspen/wptablefinder
# Acceptance Criteria

Something that makes https://github.com/everypolitician-scrapers/turkey-tbmm-wikipedia much simpler
# Not Required

We don't actually need (or probably even want) it to interact directly with Wikipedia, or be coupled to Wikipedia formatting in any way. This should operate on the raw HTML that we get by scraping, and should in theory work with Tables from _any_ source.
# Prerequisites
# Related Issues
# Due Date
# Design?
# Text?
# Bloggable?

**Comment by tmtmtmtm** [comment]
A useful initial test case is https://tr.wikipedia.org/wiki/TBMM_24._d%C3%B6nem_milletvekilleri_listesi, where most of the tables are simple, but Kilis and Kocaeli have spans.

**Comment by tmtmtmtm** [comment]
https://github.com/siuying/table_parser looked vaguely plausible, but I couldn't work out how to extract the information from it at the end. It was entirely unclear whether it was even able to correctly parse https://en.wikipedia.org/wiki/List_of_MPs_elected_in_the_Mongolian_legislative_election,_2016

**Comment by tmtmtmtm** [comment]
Based on https://www.npmjs.com/package/cheerio-tableparser, I threw together:

``` ruby
def expand_table(table)
  grid = []

  table.css('tr').each_with_index do |row, curr_x|
    row.css('td, th').each_with_index do |cell, curr_y|

      rowspan = cell.remove_attribute('rowspan').value.to_i rescue 1
      colspan = cell.remove_attribute('colspan').value.to_i rescue 1

      0.upto(rowspan - 1).each do |x|
        0.upto(colspan - 1).each do |y|
          curr_y += 1 while (grid[curr_x + x] ||= [])[curr_y + y]
          grid[curr_x + x][curr_y + y] = cell
        end
      end
    end
  end

  new_table_from(grid)
end

def new_table_from(grid)
  Nokogiri.HTML("<table>" + grid.map { |c| "<tr>" + c.map(&:to_html).join + "</tr>" }.join + "</table>")
end
```

This attempts to turn it back into an actual HTML `table` at the end, though does so very clumsily (and loses any attributes on the original `table` or `tr`s. There's almost certainly a clean way to use Nokogiri's HTML generation to inject these all back into the original (and also to make this much more ruby-ish) at which point we could turn this into a nifty little library, but this version was Good Enough For Now™

cc: @chrismytton

**Comment by chrismytton** [comment]
This library now exists: [table_unspanner](https://github.com/everypolitician/table_unspanner).
