### ISSUE TITLE
Expose more gender information

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#525]
# Problem

Currently we just expose a simple `male`/`female`/`other` gender in the Popolo JSON but in some places we have richer underlying data such as whether the person is transgender, what gender they were born as, what date their gender changed etc. It would be good to expose that somehow.
# Proposed Solution

I'm not sure exactly where or how we'd expose this data currently, so I'm open to suggestions!
# Acceptance Criteria

Consumers of the data shouldn't need to rummage through source data to get richer gender information.
# Not Required

We might want to expose other bits of richer data in a similar way, but lets just focus on gender first and then see what we learn from that.
# Prerequisites

None.
# Related Issues
- https://github.com/everypolitician/everypolitician-data/pull/18543 was the original change that triggered this issue
# Due Date

None.
# Design?

No.
# Text?

However we decide to expose it that will need to be documented, so yes.
# Bloggable?

Yes.

**Comment by tmtmtmtm** [comment]
I think that this is too complicated to include in EveryPolitician data — this can be expressed more easily within Wikidata, and could be obtained from there if someone really needs it.
