### ISSUE TITLE
Don't check scraped-pages-archive branches of scrapers on travis

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#570]
# Problem

Travis is currently running on all pushes to `scraped-pages-archive` branches, and failing — e.g. 
* https://travis-ci.org/everypolitician-scrapers/belarus-house-of-representatives-2016/builds/198549306
* https://travis-ci.org/everypolitician-scrapers/togo-national-assembly/builds/198552420
* https://travis-ci.org/everypolitician-scrapers/turks-and-caicos-assembly/builds/198580070

# Proposed Solution

Turn off checking for this branch: https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches

**Comment by sagepe** [comment]
The `scraped-pages-archive` branch doesn't have a `.travis.yml`, so we've tried setting the “Build only if .travis.yml is present?” option on for these repositories to stop these builds.
