### ISSUE TITLE
Ensure tests fail against master

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#573]
# Problem

We currently aren't strict enough about writing regression tests before adding a feature. This means that test coverage slowly decreases over time and software quality slowly declines.

# Proposed Solution

As part of the Travis build run the tests and make sure that they _fail_ against the library code on `master` but pass on the topic branch. This will force us to be more rigorous about writing tests for all new code.

We will need some way of circumventing this for things such as documentation additions, refactorings etc, but will a bit of handwaving this can probably be done by Adding some known text into the title or body of the issue or with a label that gets added before the issue is created.

# Acceptance Criteria

Adding a pull request where the tests still pass on `master` should _fail_ the Travis build, as that implies that there wasn't a regression test added.

# Not Required

This doesn't need to be particularly complex for the first pass, just a simple shell script wrapper to run on Travis.

# Prerequisites

None.

# Related Issues

An initial version of this done at the Leeds team meeting as a spike by @mhl, @tmtmtmtm and me is in https://github.com/everypolitician/everypolitician-popolo/pull/122.

# Due Date

Would be good to get a version of this running in several places fairly soon so we can get some feedback on how useful/painful this will be.

# Design?

No.

# Text?

No.

# Bloggable?

Possibly.

**Comment by tmtmtmtm** [comment]
I think the main thing missing here atm is the ability to disable it on PRs that marked as being a refactoring.

**Comment by mhl** [comment]
> I think the main thing missing here atm is the ability to disable it on PRs that marked as being a refactoring.

I've added a commit (well, several, including fixups :)) that skips the check if "refactor" (case-insentively) is a substring of the pull request title, which seems like a reasonably simple approach.

**Comment by chrismytton** [comment]
This script should probably eventually become part of a shared `everypolitician-test` library - see https://github.com/everypolitician/everypolitician/issues/584 for more details on that.

**Comment by chrismytton** [comment]
I've introduced this in Scraped here - https://github.com/everypolitician/scraped/pull/64.

**Comment by chrismytton** [comment]
I've just written this in https://github.com/everypolitician/everypolitician-popolo/pull/122#issuecomment-280035053 but adding it here for visibility:

This change isn't going to be as simple as we'd hoped. Travis does `git clone --depth=50 --branch=check-tests-fail-on-target`, which implies the `--single-branch` option, which means there is no history for the `master` branch available at the point where we're doing the build.

**Comment by chrismytton** [comment]
Latest version of this script can be seen in https://github.com/everypolitician/scraped/pull/67.

**Comment by chrismytton** [comment]
https://github.com/everypolitician/scraped/pull/67 has been merged so this is now done, yay! 🎉 

https://github.com/everypolitician/everypolitician/issues/588 has been opened to track actually adding this script to our repositories.
