### ISSUE TITLE
Nigeria: Ensure all currently represented parties have Wikidata pages

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#603]
We need to generate P39 QuickStatements, which means that we need to ensure that the target for every P4100 already exists (or create any that don't)

**Comment by tmtmtmtm** [comment]
These all currently exist, and are reconciled in [Representatives/sources/manual/group_wikidata.csv](https://github.com/everypolitician/everypolitician-data/blob/master/data/Nigeria/Representatives/sources/manual/group_wikidata.csv) (the Senate versions are a subset of these)

**Comment by lucychambers** [comment]
Added research information to #606. Closing.
