### ISSUE TITLE
Nigeria: Ensure Wikidata items exist for all elections to current term

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#604]
(including by-elections)

**Comment by lucychambers** [comment]
Unsure if we have this data. Tony to lead research. May be able to set this as "by-election" if we can't find out specific by-election info.

**Comment by tmtmtmtm** [comment]
Wikidata currently only has a single item that is a by-election in Nigeria: http://tinyurl.com/y7mh74kz

There may be others without this modelling (especially as this one didn't have those fields until I added them), but as this appears to be the only recent one with a enwiki page, I'm not hopeful.

There have, however, been multiple recent by-elections, e.g.:

* http://dailypost.ng/2017/04/27/inec-declares-accord-party-winner-warri-election/
* http://www.premiumtimesng.com/regional/ssouth-west/236240-osun-election-apc-pdp-candidates-confident-victory.html
* http://dailypost.ng/2017/07/08/osun-west-election-accreditation-voting-commence/

and many others found when googling "Nigeria by-election"

I suspect we're simply going to have to either leave this field blank, or set it to Q1057954

**Comment by lucychambers** [comment]
Also main legislative election, 2015: https://www.wikidata.org/wiki/Q28941248

@tmtmtmtm - do we have a list of things which should be on an election page? I can't see on https://www.wikidata.org/wiki/Wikidata:EveryPolitician. 

I have added territorial jurisdiction but let me know if anything else is missing that should be there.

**Comment by tmtmtmtm** [comment]
@lucychambers WikiProject Elections got subsumed into WikiProject Politician Infoboxes at some point: https://www.wikidata.org/wiki/Wikidata:WikiProject_Politics_infoboxes#Welcome_to_WikiProject_Elections

Its model looks a little out of date, but it's the closest I know of atm.

**Comment by lucychambers** [comment]
OK - if I understand this correctly. We only need the existence of the election items for the next step to progress, so I would add adding correct details *to* the election as a separate task for after we have the other bits done. Please let me know if you disagree :)

**Comment by tmtmtmtm** [comment]
@lucychambers 👍

**Comment by lucychambers** [comment]
Opened #607 - closing this one.
