### ISSUE TITLE
Twitter scrapers failing with 'No such list'

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#610]
Many of our twitter scrapers fail with an error: ```Sorry, that page does not exist. (Twitter::Error::NotFound)```

This happens fairly consistently on Morph, even for scrapers that run fine locally, e.g. https://morph.io/everypolitician-scrapers/twitter-scotland

**Comment by tmtmtmtm** [comment]
https://morph.io/everypolitician-scrapers/twitter-list-switzerland, OTOH, always seems to run just fine.

**Comment by tmtmtmtm** [comment]
https://morph.io/everypolitician-scrapers/twitter_list_South_Korea is almost identical to the Scottish version, so might be useful to track down what's going on.

**Comment by chrismytton** [comment]
I've just spent an hour investigating this. It seems to be a transient error at Twitter's end.

To test this I opened https://twitter.com/lechinoise/lists/politics-arg in an incognito Chrome window and refreshed it a number of times. Sometime the page 404s and looks like this:

![screen shot 2017-08-16 at 16 46 35](https://user-images.githubusercontent.com/22996/29372244-7cdb2b82-82a2-11e7-8969-7d1743b23d6b.png)

But a lot (most?) of the time it works and looks something like this:

![screen shot 2017-08-16 at 16 46 19](https://user-images.githubusercontent.com/22996/29372262-88de1322-82a2-11e7-9e58-e94f87216b00.png)

There doesn't seem to be any consistency with how often this happens either.

I've contacted Twitter support about this, so hopefully they'll be able to fix this problem at their end, though the message it gave me after submitting the support request suggests they probably won't be back in touch:

> Thanks! Though we cannot respond to individual reports, the information provided helps us make Twitter better for everyone. We appreciate your help!

**Comment by tmtmtmtm** [comment]
> It seems to be a transient error at Twitter's end

Erk, that's pretty nasty.

>  a lot (most?) of the time it works

Unfortunately we're getting the reverse of that on morph.

For example https://morph.io/everypolitician-scrapers/twitter-scotland ran successfully every day until June 29th, and since then has only completed successfully three times compared to about fifty failures

https://morph.io/everypolitician-scrapers/twitter-list-austria-nr-abgeordnete also stopped working on the same date, and has only completed successfully once since. https://morph.io/everypolitician-scrapers/twitter-list-spain-congreso has failed every day since then.

Is there anywhere else we could ask about this? If it's a general problem, it seems like it must be affecting other people too.

**Comment by chrismytton** [comment]
@tmtmtmtm My understanding is that the chance of a 404 _on a single page_ is something like one in five, but most of the scrapers are retrieving lists of people that span multiple pages, so each subsequent page fetch is another chance for it to 404. So while loading a single page works most of the time, loading multiple pages of results increases the chance that we'll encounter a 404.

> Is there anywhere else we could ask about this? If it's a general problem, it seems like it must be affecting other people too.

I'm not sure, a quick Google around revealed [this post](http://follows.com/blog/2016/01/the-best-way-contact-twitter-through-email-support), which states:

> The third and highest priority method of contact, as far as Twitter is concerned, is their pile of support forms.

Which is the form I've already filled in. Not sure where else I could ask, any suggestions?

**Comment by tmtmtmtm** [comment]
> My understanding is that the chance of a 404 on a single page is something like one in five, but most of the scrapers are retrieving lists of people that span multiple pages, so each subsequent page fetch is another chance for it to 404. So while loading a single page works most of the time, loading multiple pages of results increases the chance that we'll encounter a 404.

Ah. That makes sense.

But that also implies that we can probably work around this by trapping a 404 and retrying a couple of times, no?

**Comment by chrismytton** [comment]
> But that also implies that we can probably work around this by trapping a 404 and retrying a couple of times, no?

The error is coming from deep inside the [Ruby Twitter gem](https://github.com/sferik/twitter), so might have to do some delicate monkey patching, but yep, patching it to retry seems like a plausible approach!

**Comment by chrismytton** [comment]
I've opened a [pull request on the `twitter_list` gem](https://github.com/everypolitician/twitter_list/pull/9) which should retry requests up to 10 times before failing. This should allow us to get most scraper working again, while still erroring for lists that have genuinely been deleted or renamed.

I'm going to try that branch with a few scrapers before merging it, to check that it's actually having the desired effect.

**Comment by chrismytton** [comment]
That seems to have worked! I've updated the following scrapers:

- https://github.com/everypolitician-scrapers/twitter-argentina
- https://github.com/everypolitician-scrapers/twitter-israel
- https://github.com/everypolitician-scrapers/twitter-list-netherlands

So these should now be working _most_ of the time.

Other scrapers will need to have the `twitter_list` gem updated by running `bundle update twitter_list` and then committing the result.

**Comment by chrismytton** [comment]
I've closed this for now. If it seems that this fix isn't having the desired effect after updating the `twitter_list` gem then please reopen 👍

**Comment by tmtmtmtm** [comment]
Woohoo! Thanks @chrismytton

**Comment by tmtmtmtm** [comment]
@chrismytton most of these are now running fine 🎉  — but the one you actually seem to have tested this on — https://morph.io/everypolitician-scrapers/twitter-argentina — doesn't seem to have run successfully since you did this…

**Comment by chrismytton** [comment]
@tmtmtmtm That's very odd. When I click "Run scraper" on https://morph.io/everypolitician-scrapers/twitter-argentina it seems to run implausibly quickly, almost as if the scraper isn't running at all? Perhaps a morph issue?

**Comment by tmtmtmtm** [comment]
@chrismytton I pushed a new Gemfile, which usually convinces morph something has changed. Sure enough, this time it went through the full "Installing dependencies" phase etc … but then still errored out at the end
