### ISSUE TITLE
Bot to work around QuickStatements problems with P39s

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#615]
# Problem

[QuickStatements](https://tools.wmflabs.org/wikidata-todo/quick_statements.php) is a great tool for adding lots of information to Wikidata quickly. It isn't the most user-friendly tool (though that's somewhat deliberate to help filter people using it), but it's certainly possible to teach people we're working with how to use it to insert data.

However, it doesn't work well with P39 (Position Held) statements under many circumstances… and that is one of the most frequent properties we work with.

In general it takes a TSV of statements, such as 

```
Q567	P39	Q1939555	P2937	Q30579723	P2715	Q15062956
```
(Angela Merkel → position held: Member of the Bundestag; term: 19th Bundestag; elected in: German federal election, 2017)

and breaks it down into separate statements, which effectively do:

1. Q567 → find_or_create P39:Q1939555
2. Q567 → find_or_create P39:Q1939555 → add_qualifier P2937: Q30579723
3. Q567 → find_or_create P39:Q1939555 → add_qualifier P2715: Q15062956

with the general idea that by the time it hits stages 2 and 3, number 1 will have created the requisite P39 statement to attach the qualifier to.

However, unlike most other properties, where a given subject/object pair should only occur once, political positions tend to be held multiple times (e.g. Angela Merkel has been a Member of the Bundestag 7 times so far). This means that when QuickStatements runs each of the above statements it finds a pre-existing membership (e.g. for the 12th Bundestag), and will add the new qualifiers to _that_, thus creating incorrect data.

We have talked to Magnus about this, and he believes that the problem will likely be sorted (if not by default, then at least by setting an option) in a future version, once it is possible to supply the statements you want as JSON rather than TSV.

We have tried finding modelling workarounds — e.g. having a new per-term Membership item for, e.g. "Member of the 19th Bundestag". This removes 95% of the problem cases (there are still issues where someone holds _that_ position more than once, e.g. if they change party mid-term, or in countries where joining the cabinet means leaving the legislature, but on a reshuffle might end up back in the legislature), but has not gained widespread acceptance within the Wikidata community.

At the moment, therefore, the only way to add the list of the winners of this weekend's German election is going to be by hand (at least for anyone who has a previous P39:Q1939555 pair).

We therefore need a new tool that could inject these.

# Proposed Solution

We have various approaches we could take for this, but I'm working off two basic assumptions:

1. We want a tool that can be used by other people, not just ourselves
2. We want it be as QuickStatements-like as possible (in terms of data format, interface, etc.) 

The rough approach _I_ would probably take, then is:

* Create a command-line bot that accepts QuickStatements-like commands, (but doesn't have the problem above) and inserts them via the API
    * This would insert each new statement (without looking for existing ones), with the specified qualifiers/sources. (I'm not sure if the API allows for doing that in one call, or whether we need to emulate the QS workflow, but if the latter, we would keep the underlying ID of the created statement and use it directly for each of the qualifier/source additions)
    * It would probably use `pywikibot`, as that will take care of most of the fiddly details around things like throttling, and make it easier for us to get the bot approved.
* Once that is working correctly, provide a QS-like web interface to that so that authenticated users can use the tool

# Acceptance Criteria

Our partners can add P39s for all the winners of the German elections.

# Not Required

* We don't need to provide the full functionality of QuickStatements. For example, we don't need to enable people to CREATE new items. Anything that _can_ be done via QuickStatements, _should_ be done that way. (We might even want to simply refuse to add anything other than P39 statements.)
* We don't need to worry about people creating duplicate statements. Users will be expected to pre-filter their list of commands to ones they know are safe. If someone makes a mistake, it's up to them to clean it up (PetScan could delete all the wrong statements, and then they can re-insert them by using this tool again)

# Due Date

There is a lead time for bot approval, so we need to start that process ASAP. We can then probably use the German results as our official test-run, before getting the bot approved for more widespread use.

**Comment by chrismytton** [comment]
Some useful links:

- https://www.mediawiki.org/wiki/Manual:Pywikibot/Scripts#Wikidata has some useful examples to learn from / copy
- https://www.mediawiki.org/wiki/Manual:Pywikibot/Wikidata has a Wikidata-specific example
- https://github.com/wikimedia/pywikibot-core/blob/master/scripts/freebasemappingupload.py is a simple example case that we might be able to copy
- https://www.mediawiki.org/wiki/Manual:Pywikibot/PAWS

**Comment by chrismytton** [comment]
First task is to do some investigation to see what would be involved in reading a file with lines like `Q567    P39    Q1939555    P2937    Q30579723    P2715    Q15062956` and pushing those through the API.

**Comment by chrismytton** [comment]
This seems to be a vital page of the Pywikibot documentation when interacting with Wikidata:

https://doc.wikimedia.org/pywikibot/api_ref/pywikibot.html?highlight=itempage#pywikibot.ItemPage

For some reason that's not linked to from the [API reference page](https://doc.wikimedia.org/pywikibot/api_ref/index.html).

**Comment by chrismytton** [comment]
There's a reasonably good example of adding a claim with a qualifier in the pywikibot tests:

https://github.com/wikimedia/pywikibot-core/blob/01f6d4b408325226bc766f78dff1ad91b7f4ac5a/tests/wikibase_edit_tests.py#L69

Using that code I managed to piece together this script for creating a new P39 statement and adding a qualifier to it:

```python
import pywikibot

site = pywikibot.Site()
repo = site.data_repository()

# Get the item we want to modify
item = pywikibot.ItemPage(repo, 'Q42')
item.get()

# Get the item which we want to set as the target of the claim (e.g. "Member of the 14th Bundestag")
position = pywikibot.ItemPage(repo, 'Q123')
position.get()

# Create a new P39 statement pointing to Q123
position_held = pywikibot.Claim(site, 'P39')
position_held.setTarget(position)

# Add the claim to the item.
item.addClaim(position_held)

# Add a start date (P87 on test.wikidata.org) qualifier to the claim
start_date = pywikibot.Claim(site, 'P87', isQualifier=True)
start_date.setTarget(pywikibot.WbTime(year=2017, month=9, day=20))
position_held.addQualifier(start_date)

# Get a party for use in a qualifier
party = pywikibot.ItemPage(repo, 'Q1488')
party.get()

# Create another qualifier, this time pointing to a party
party_position = pywikibot.Claim(site, 'P43018', isQualifier=True)
party_position.setTarget(party)
position_held.addQualifier(party_position)
```

**Note**: My local pywikibot is configured to use https://test.wikidata.org, so some `P` and `Q` values may be slightly different to regular Wikidata.

**Comment by chrismytton** [comment]
I've created [everypolitician/position_statements](https://github.com/everypolitician/position_statements), which takes the code above and turns it into a command line tool which accepts a TSV of QuickStatements. At the moment it only handle qualifiers, not sources, and only works with items, strings and time datatypes.

**Comment by chrismytton** [comment]
High level summary of where we're at with PositionStatements:

## What's works right now

- Parsing QuickStatements-like lines from a TSV file
- Extracting item, string and time datatypes from qualifier values
- Adding P39 claims to an item
- Adding qualifiers to that P39 claim

## Other bits needed for initial version

- Tidy up the code (it's mostly just untested procedural code at the moment)
- Only accept P39 statements (the implementation means anything goes currently) https://github.com/everypolitician/position_statements/issues/4
- Validate that the input is sane (e.g. items start with Q, properties start with P, statements have the correct number of items etc) https://github.com/everypolitician/position_statements/issues/2
- Add the ability to create sources as well as qualifiers https://github.com/everypolitician/position_statements/issues/1

**Comment by lucychambers** [comment]
Hi Chris - this is great. I think we'd be tackling these in the following order: 

* Add the ability to create sources as well as qualifiers everypolitician/position_statements#1 (Required for the German use-case) 

[We've reached minimum viable for purposes of testing with German data]

* Validate that the input is sane (e.g. items start with Q, properties start with P, statements have the correct number of items etc) everypolitician/position_statements#2

[Can "officially" release] 

* Only accept P39 statements (the implementation means anything goes currently) everypolitician/position_statements#4

[We've reached bonus for release] 

Code tidy up can come when we've run a test or two and we know if any changes need to be made so that the tidy up is targeted around addressing those!

**Comment by chrismytton** [comment]
@lucychambers sounds good to me!

**Comment by chrismytton** [comment]
> - Add the ability to create sources as well as qualifiers everypolitician/position_statements#1 (Required for the German use-case)
>
> [We've reached minimum viable for purposes of testing with German data]

I've added support for sources in https://github.com/everypolitician/position_statements/pull/5.

**Comment by chrismytton** [comment]
> - Only accept P39 statements (the implementation means anything goes currently) everypolitician/position_statements#4
>
> [We've reached bonus for preliminary release]

Restricted to P39 statements in https://github.com/everypolitician/position_statements/pull/6.

**Comment by chrismytton** [comment]
> - Validate that the input is sane (e.g. items start with Q, properties start with P, statements have the correct number of items etc) everypolitician/position_statements#2
>
> [Can "officially" release]

Basic validations added in https://github.com/everypolitician/position_statements/pull/8

**Comment by lucychambers** [comment]
UI components split out into #618. Based off that - @chrismytton - please feel free to close this ticket or comment with anything that is still outstanding!

**Comment by chrismytton** [comment]
@lucychambers Thanks! Yep I think this is done-enough now, any issues with the bot can now be raised in the [position statements bot issue tracker](https://github.com/everypolitician/position_statements/issues).
