### ISSUE TITLE
create a bot to show the historic holders of a Wikidata position

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#617]
We have previously attempted to use Listeria to generate a history of, for example, everyone who has been the Prime Minister of the United Kingdom.

This has had at least two significant problems:

1. It is very difficult to highlight data we suspect is problematic. (https://www.wikidata.org/w/index.php?title=Talk:Q737115&oldid=526099610 was an attempt at this, but it's rather awkward to implement, or to understand)
2. Listeria doesn't cope with someone holding the same position more than once (see, for example https://www.wikidata.org/w/index.php?title=Talk:Q14211&oldid=517180090)

So we should build our own Listeria-like tool that generates tables of data for all known holders of a specified position (NB: only positions that are expected to only have a single officeholder at a time), highlighting data we believe to be problematic.

**Comment by tmtmtmtm** [comment]
I've made a script to generate a basic table of data: https://github.com/everypolitician/wikidata-position-history

This attempts to detect a few problematic data cases, and wraps them in a warning — see, for example Robert Peel and Robert Walpole at  https://www.wikidata.org/w/index.php?title=Talk:Q14211&oldid=565816256

Currently the output needs to be pasted in by hand — I haven't attempted yet to turn this into an actual bot.

**Comment by zarino** [comment]
@tmtmtmtm Is there anything problematic about the diagonal layout, specifically, of https://www.wikidata.org/w/index.php?title=Talk:Q737115&oldid=526099610 ?

For instance, now you’ve opened up the possibility of using Ruby to output the markup, we could upgrade that diagonal layout to _also_ highlight the columns where data doesn’t match up, in a big red background or whatever. Do you think that would help, or was there something else you wanted to avoid about our previous "diagonal" attempt?

**Comment by tmtmtmtm** [comment]
@zarino it's been pretty much impenetrable to anyone I've showed it to. It starts with the information that is least likely to be accurate/interesting/useful, and requires people to scroll simultaneously horizontally and vertically to get to the recent information — if someone simply scrolls down, they end up with a completely empty screen. I think it was a really clever attempt to work around the constraints we had with Listeria, but I fear it's fundamentally a dead end. I'm open to persuasion on that, of course, but if we're removing the previous constraints, I think I'd go with something much simpler, and more accessible to people used to normal simple wikitables.

**Comment by zarino** [comment]
Ok @tmtmtmtm that is really useful feedback. Two concrete changes then:

* Start with most recent data at the top.
* Try to avoid horizontal scrolling.

What are your thoughts on something more like this: http://jsfiddle.net/zarino/n1y8v62s/embedded/result/

![screen shot 2017-10-12 at 10 35 52](https://user-images.githubusercontent.com/739624/31489623-2c644972-af39-11e7-94cc-a0ea57655e61.png)

**Comment by tmtmtmtm** [comment]
@zarino my suspicion is that people are still going to have difficulty following what's going on there. But I'd be interested in getting some feedback to find out. Have you tried testing this on some other people?

**Comment by tmtmtmtm** [comment]
@zarino and I worked together on putting a new design for this in place. Current evolution of it is 'live' at https://www.wikidata.org/w/index.php?title=Talk:Q14211&oldid=579454726

I think this is Good Enough For Now™, but currently it only works by running https://github.com/everypolitician/wikidata-position-history/blob/master/history.rb manually and pasting the output. We still need to turn this into a bot that can be triggered from a template and will update automatically (similarly to Listeria/Prompts)

**Comment by mhl** [comment]
What would you suggest is the template name and usage we should use for this? e.g. perhaps: `{{PositionHoldersHistory|Q14211}}` ?

To set out how I imagine this working, the `PositionHoldersHistory` template attempts to transclude the subpage `/position_held_history_Q14211` (or whatever the item is) and if not outputs [something helpful - "manual refresh" + "purge" buttons?]. The bot code does the following:
* Takes a page title as a parameter
* For each `{{PositionHoldersHistory|Q...}}` template on the page:
   * Untemplates the parameter to get the item ID
   * Runs the code in history.rb to generate output and edits that into `/position_held_history_Q14211`

Once that basically works, we'd need to:
* Request permission for the bot
* Add a minimal sinatra app that responds to a GET request to rewrite that page (with the usual "yes, this really shouldn't be a GET request" proviso) so it can be triggered manually from a button on the page
* Add that Sinatra app to the WMF tools service https://tools.wmflabs.org - see:
    * https://github.com/everypolitician/prompter/blob/master/script/toolforge-start
* Set up periodic running of the bot on every page found that includes the template, as compare_with_wikidata does:
    * https://github.com/everypolitician/prompter/blob/master/script/toolforge-cronjob
    * https://github.com/everypolitician/prompter/blob/master/script/update-all-prompts

This follows closely the `compare_with_wikidata` method, I think.

**Comment by tmtmtmtm** [comment]
@mhl, that all sounds plausible. One slight hesitation is that transcluding a second page will have the same problem with prompts, whereby it's slightly awkward to add the page to your watchlist, so I think it would be preferable if the page itself was rewritten, rather than sub-page. (Note, that's only "preferable", rather than a hard requirement — if it's significantly problematic, this way would be OK.)

(Also: I don't think it's necessary to allow more than one call to the template from a single page. If the implementation ends up making it possible, it's a bonus, but if the implementation precludes it, that's OK too.)

I suspect we'll also want to turn the bulk of code in `history.rb` into a library the Sinatra app can use, rather than directly running it as a script, but that hopefully shouldn't be particularly tricky.

**Comment by tmtmtmtm** [comment]
On naming and usage, I wonder if `PositionHolderHistory` might be better than Holder**s**, as a subtle reinforcement of the underlying requirement that this is only for positions that a single person should hold at a time?

I also suspect named parameters might be more future proof too, as I can see us wanting to add other options later: `{{PositionHolderHistory|id=Q…}}`?

**Comment by mhl** [comment]
> I suspect we'll also want to turn the bulk of code in history.rb into a library the Sinatra app can use, rather than directly running it as a script, but that hopefully shouldn't be particularly tricky.

Right, I was assuming that by analogy with `compare_with_wikidata`.

> @mhl, that all sounds plausible. One slight hesitation is that transcluding a second page will have the same problem with prompts, whereby it's slightly awkward to add the page to your watchlist, so I think it would be preferable if the page itself was rewritten, rather than sub-page. (Note, that's only "preferable", rather than a hard requirement — if it's significantly problematic, this way would be OK.)

Trying to remember how we did this before: if we were to rewrite this page, would that be using a sentinel HTML comment to mark the end, as https://github.com/everypolitician/mediawiki-page-replaceable_content did?

**Comment by tmtmtmtm** [comment]
> would that be using a sentinel HTML comment

Either that, or an explicit closing template call, similar to how Listeria requires a `{{Wikidata list end}}`. That way is significantly more awkward for users though, so if it can be done from our end, that would be significantly better, yes.

**Comment by tmtmtmtm** [comment]
Currently waiting on bot flag, and there may be some lingering code-cleaning required, but from my POV this is essentially Done for now. Any further tweaks can be ticketed separately.
