### ISSUE TITLE
Malformed Wikinews URLs

### ISSUE THREAD

**Issue by wfdd** [everypolitician/everypolitician#646]
## Legislature

A subset of legislatures harvested from Wikidata.

## Problem

In Popolo JSON files partial Wikinews URLs are prefixed with xxwikinews.wikipedia.org instead of xx.wikinews.org ([example](https://github.com/everypolitician/everypolitician-data/blob/b3a8469cb50e251226aabef5501a07af21825222/data/Northern_Cyprus/Assembly/ep-popolo-v1.0.json#L553)).  The reason for this is that the column names in the source CSVs are in the format wikipedia__xxwikinews and are therefore handled as if they were Wiki*pedia* URLs by the converter.

## Proposed Solution

This would (first) require fixing in wikidata-fetcher or wikisnakker, either to filter out Wikinews links or to label them accordingly.

**Comment by tmtmtmtm** [comment]
Hi @wfdd, this was fixed a while back now, but I'm curious whether this was something you just happened to notice and thought should really be fixed, or whether it's something you're actually *using*? (In other words, I'm considering removing Wikinews, Wikiquote, and Wikisource links, but if you're actually using them, them I'm happy to leave them)

**Comment by wfdd** [comment]
Hi Tony, it was just something I’d noticed while tinkering with a Wikidata scraper.

**Comment by tmtmtmtm** [comment]
Good to know, thanks @wfdd
