### ISSUE TITLE
Handle generating ids when there are duplicate names

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#647]
When you have a country where two person have the same name the automatic id generation doesn't work correctly. Ideally it should either warn you about the conflict or it should resolve it by appending a number to the generated id, e.g. `slug-1`, `slug-2` etc.

**Comment by tmtmtmtm** [comment]
This doesn't seem to have been enough of an issue in practice to ever do something about, and if it were to show up now, I think that would mostly just be an incentive to more quickly switch that source to being Wikidata-driven. Closing as WONTFIX
