### ISSUE TITLE
Fix zoom controls on JQVmap

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#74]
The + and - controls on the map are slightly off — something in the CSS must be clashing:

![screen shot 2015-05-25 at 16 10 15](https://cloud.githubusercontent.com/assets/57483/7798989/9615d204-02f8-11e5-82de-03797848e8df.png)

**Comment by dracos** [comment]
It's the `border-box` on all elements.

**Comment by tmtmtmtm** [comment]
Closed by #84
