### ISSUE TITLE
Nicely designed basic page template

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#8]

**Comment by wrightmartin** [comment]
Here's some wireframes based on our earlier conversation. It's likely I've got some stuff wrong/misinterpreted it so please say.

It's pretty barebones, but I think it's achievable (except maybe the drag and drop stuff?)

![homepage](https://cloud.githubusercontent.com/assets/2292925/6211729/2bd91ba0-b5d5-11e4-97c8-6c2e44f709eb.png)

![step 2](https://cloud.githubusercontent.com/assets/2292925/6211730/2bdb2fee-b5d5-11e4-9217-d5ad6177f579.png)

![problem](https://cloud.githubusercontent.com/assets/2292925/6211728/2bd88b0e-b5d5-11e4-93f2-28af3b40ec5c.png)

![about](https://cloud.githubusercontent.com/assets/2292925/6211727/2bd5e73c-b5d5-11e4-8aa3-e2d378aaf0ed.png)

**Comment by tmtmtmtm** [comment]
Excellent, thanks.

The drag and drop bit looks fairly doable (insert suitable handwaving here), with at least the Basic version of https://blueimp.github.io/jQuery-File-Upload/ — though it's not completely necessary for a v0.0.1

For the map, I'd been playing with the simple colour-the-entire-country approach from Google Charts Map Visualization: http://jsfiddle.net/tndze90a/ — was your dot-based approach just a placeholder for a generic map, or you think it would look better like that?

**Comment by wrightmartin** [comment]
@tmtmtmtm great!

The map was just a placeholder, dw about any weird functionality there. 

I'll start coding up the basics now

**Comment by wrightmartin** [comment]
If you know how to change the colours of the paint area on the google map that would be handy

**Comment by tmtmtmtm** [comment]
@wrightmartin Does https://developers.google.com/chart/interactive/docs/gallery/geochart#coloring give you what you need?

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/mysociety/openpoliticians/commit/c68ae86df8483dcf4152e6f1e2d546cc41c273a8
