### ISSUE TITLE
EveryPolitician favicon and social media avatar

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#90]
possibly based on Martin's designs (https://github.com/everypolitician/viewer-sinatra/issues/279)

Should ideally be usable as the Github icon too, especially as it's re-used on things like Morph to show us downloading data (e.g. https://morph.io/openaustralia/aus_mp_contact_details)

**Comment by zarino** [comment]
Favicon and Github avatar done. Which social media icons do you need? Just Twitter? (I can prepare images at the optimum sizes if you let me know the services)

**Comment by tmtmtmtm** [comment]
Those are the only two we'll be using at the minute. We don't actually have a twitter account, AFAIK.

**Comment by tmtmtmtm** [comment]
Closed by #387
