### ISSUE TITLE
Store underlying Twitter IDs

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#92]
~~These tend to appear sometimes under `links` and sometimes under `contact_details` (and in a wide variety of different formats). They should probably be in both: as a full `http://twitter.com/name` version in `links`, and the `@name` version in `contact_details`.~~ (This part is now done)

 We should probably also store the underlying ID under `identifiers` too, to cope with cases where they change their name (e.g. in the UK when they add/remove "MP")

**Comment by tmtmtmtm** [comment]
These tend to appear sometimes under `links` and sometimes under `contact_details`. They should probably in both: as a full `http://twitter.com/name` version in `links`, and the `@name` version in `contact_details`. It might also be worth storing the underlying ID under `identifiers` too, for cases where they change their name (e.g. in the UK when they add/remove "MP")

**Comment by tmtmtmtm** [comment]
The handles in the CSV are [now standardised](https://github.com/everypolitician/everypolitician-data/blob/ef8c42cd89ee1a9110cc1afb720aaaaebb08dd74/rakefile_csvs.rb#L28-L41) — we still need to do it for the JSON. We _could_ do this within [CSV-to-Popolo](https://github.com/tmtmtmtm/csv_to_popolo), but it's probably best to do it in `rakefile_transform`.

**Comment by tmtmtmtm** [comment]
@andylolz has mused about possibly doing this one…

**Comment by andylolz** [comment]
I’ve made a bit of a start over here: https://morph.io/andylolz/ep-twitter-ids

**Comment by tmtmtmtm** [comment]
Ah, great! 

You're probably better starting at https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/countries.json, though — that's the definitive most-recent version — rather than getting that indirectly through the DATASOURCE in viewer-sinatra repo (think of that website as just being one of many apps that derive from the data, and might be out of sync with it etc.)

**Comment by tmtmtmtm** [comment]
The JSON now includes standardised Twitter details in both `contact_details` and `links`.

Leaving this ticket open for the part where we also include the underlying identifier, which is probably still best done via scheduled morph-based lookups.

**Comment by andylolz** [comment]
Hi @tmtmtmtm!

I’ve had another look at this today: https://morph.io/andylolz/ep-twitter-ids

**Comment by andylolz** [comment]
Just looking at this again. I’ve made some changes to:
https://morph.io/andylolz/ep-twitter-ids
…though it still needs some work.

I’ve used the fields described in http://docs.everypolitician.org/submitting.html, but:
- while `identifier__xxx` is documented, it’s not clear `link__xxx` or `contact_detail__xxx` will do The Right Thing
- I’m not sure how to tell EP to remove data. I guess this is a weird thing that most scrapers don’t want to do… But here we want to flag or remove twitter IDs and handles that the twitter API doesn’t recognise

**Comment by tmtmtmtm** [comment]
Oooh, nice.

I wouldn't worry too much about matching the fields from that URL — that's what we use to import Membership data for a Legislature: we'll need a whole different process for dealing with this. 

For removed data, I'm not 100% sure what will be best. The simplest is probably to just set the ID to a known false value (I guess this depends slightly on whether everything else will mean that there definitely _is_ an ID, or whether some entries can be in a "don't know" state. A more complex version could be to write those cases to a different table.

BTW, https://github.com/everypolitician/everypolitician-python and/or https://github.com/everypolitician/everypolitician-popolo-python might help you simplify some of this considerably. (Or, that's the hope anyway. Would be very interested in seeing whether it actually turns out to be true…)

**Comment by andylolz** [comment]
Thanks for alerting me to https://github.com/everypolitician/everypolitician-python and https://github.com/everypolitician/everypolitician-popolo-python – I’ve switched to using those 👍 

> The simplest is probably to just set the ID to a known false value

Yeah, so at the moment the person is added to the output table, but the twitter ID and handle are both set to null.

> A more complex version could be to write those cases to a different table.

You’re right – I’m pretty sure we need another table here in order to know what should be removed from EveryPolitician. I’ll add that in. Thanks!

**Comment by andylolz** [comment]
I’ve added [a bit of a README](https://github.com/andylolz/ep-twitter-ids/blob/master/README.md) now, including [sample output](https://github.com/andylolz/ep-twitter-ids/blob/master/README.md#sample-output).

**Comment by tmtmtmtm** [comment]
The current expectation is that we'll get this information from Wikidata rather than directly from twitter.
